import Foundation

struct L10n {
    static var current: String {
        UserDefaults.standard.string(forKey: "nova_lang") ?? "cs"
    }

    static let strings: [String: [String: String]] = [
        "cs": [
            "settings": "Nastavení", "save": "Uložit", "name": "Jméno",
            "name_placeholder": "Tvoje jméno", "city": "Domovské město",
            "city_placeholder": "Město", "language": "Jazyk",
            "voice": "Hlas asistenta", "female": "Ženský", "male": "Mužský",
            "connection": "Připojení", "connected": "Připojeno", "disconnected": "Odpojeno",
            "change_server": "Změnit server", "ready": "Připravena",
            "listening": "Poslouchám...", "thinking": "Přemýšlím...", "speaking": "Mluvím...",
            "write_nova": "Napiš Nově...", "you": "Ty",
            "connect": "Připojit", "server_title": "Připojení k serveru",
        ],
        "en": [
            "settings": "Settings", "save": "Save", "name": "Name",
            "name_placeholder": "Your name", "city": "Home city",
            "city_placeholder": "City", "language": "Language",
            "voice": "Assistant voice", "female": "Female", "male": "Male",
            "connection": "Connection", "connected": "Connected", "disconnected": "Disconnected",
            "change_server": "Change server", "ready": "Ready",
            "listening": "Listening...", "thinking": "Thinking...", "speaking": "Speaking...",
            "write_nova": "Write to Nova...", "you": "You",
            "connect": "Connect", "server_title": "Connect to server",
        ],
        "de": [
            "settings": "Einstellungen", "save": "Speichern", "name": "Name",
            "name_placeholder": "Dein Name", "city": "Heimatstadt",
            "city_placeholder": "Stadt", "language": "Sprache",
            "voice": "Assistentenstimme", "female": "Weiblich", "male": "Männlich",
            "connection": "Verbindung", "connected": "Verbunden", "disconnected": "Getrennt",
            "change_server": "Server ändern", "ready": "Bereit",
            "listening": "Höre zu...", "thinking": "Denke nach...", "speaking": "Spreche...",
            "write_nova": "Schreib Nova...", "you": "Du",
            "connect": "Verbinden", "server_title": "Mit Server verbinden",
        ],
        "fr": [
            "settings": "Paramètres", "save": "Enregistrer", "name": "Nom",
            "name_placeholder": "Ton nom", "city": "Ville",
            "city_placeholder": "Ville", "language": "Langue",
            "voice": "Voix de l'assistant", "female": "Féminine", "male": "Masculine",
            "connection": "Connexion", "connected": "Connecté", "disconnected": "Déconnecté",
            "change_server": "Changer de serveur", "ready": "Prête",
            "listening": "J'écoute...", "thinking": "Je réfléchis...", "speaking": "Je parle...",
            "write_nova": "Écris à Nova...", "you": "Toi",
            "connect": "Connecter", "server_title": "Connexion au serveur",
        ],
        "es": [
            "settings": "Ajustes", "save": "Guardar", "name": "Nombre",
            "name_placeholder": "Tu nombre", "city": "Ciudad",
            "city_placeholder": "Ciudad", "language": "Idioma",
            "voice": "Voz del asistente", "female": "Femenina", "male": "Masculina",
            "connection": "Conexión", "connected": "Conectado", "disconnected": "Desconectado",
            "change_server": "Cambiar servidor", "ready": "Lista",
            "listening": "Escuchando...", "thinking": "Pensando...", "speaking": "Hablando...",
            "write_nova": "Escribe a Nova...", "you": "Tú",
            "connect": "Conectar", "server_title": "Conexión al servidor",
        ],
        "ja": [
            "settings": "設定", "save": "保存", "name": "名前",
            "name_placeholder": "あなたの名前", "city": "ホームシティ",
            "city_placeholder": "都市", "language": "言語",
            "voice": "アシスタントの声", "female": "女性", "male": "男性",
            "connection": "接続", "connected": "接続済み", "disconnected": "未接続",
            "change_server": "サーバー変更", "ready": "準備完了",
            "listening": "聞いています...", "thinking": "考えています...", "speaking": "話しています...",
            "write_nova": "Novaに書く...", "you": "あなた",
            "connect": "接続", "server_title": "サーバーに接続",
        ],
        "zh": [
            "settings": "设置", "save": "保存", "name": "姓名",
            "name_placeholder": "你的名字", "city": "所在城市",
            "city_placeholder": "城市", "language": "语言",
            "voice": "助手语音", "female": "女声", "male": "男声",
            "connection": "连接", "connected": "已连接", "disconnected": "未连接",
            "change_server": "更改服务器", "ready": "就绪",
            "listening": "聆听中...", "thinking": "思考中...", "speaking": "说话中...",
            "write_nova": "写给Nova...", "you": "你",
            "connect": "连接", "server_title": "连接到服务器",
        ],
    ]

    static func t(_ key: String) -> String {
        strings[current]?[key] ?? strings["en"]?[key] ?? key
    }

    // MARK: - Thinking stages (granular progress)
    static let stages: [String: [String: String]] = [
        "cs": [
            "thinking": "Přemýšlím",
            "understanding": "Rozumím, pracuji",
            "analyzing": "Analyzuji",
            "reading_file": "Čtu soubor",
            "writing_file": "Píšu do souboru",
            "writing_code": "Píšu kód",
            "editing_code": "Upravuji kód",
            "running_command": "Spouštím příkaz",
            "searching_web": "Hledám na webu",
            "searching_contact": "Hledám kontakt",
            "searching_restaurant": "Hledám restauraci",
            "searching_calendar": "Hledám v kalendáři",
            "calling_api": "Volám službu",
            "processing_image": "Zpracovávám obrázek",
            "generating_response": "Formuluji odpověď",
            "composing": "Skládám odpověď",
            "explaining": "Vysvětluji",
            "recommending": "Připravuji doporučení",
            "comparing": "Porovnávám možnosti",
            "listing_steps": "Sestavuji postup",
            "summarizing": "Shrnuji",
            "warning": "Upozorňuji na rizika",
            "finishing": "Dokončuji",
            "needs_confirmation": "Potřebuji souhlas",
            "saving": "Ukládám změny",
            "browsing_results": "Procházím výsledky",
            "searching_deeper": "Hledám podrobněji",
            "preparing_report": "Připravuji report",
            "fetching_news": "Stahuji zprávy",
            "analyzing_news": "Analyzuji zprávy",
            "checking_weather": "Zjišťuji počasí",
            "searching_wiki": "Hledám na Wikipedii",
            "checking_exchange": "Zjišťuji kurzy",
            "searching_cinema": "Hledám program kin",
            "searching_places": "Hledám místa",
            "reading_email": "Čtu emaily",
            "adding_calendar": "Zapisuji do kalendáře",
            "searching_files": "Procházím soubory",
            "searching_code": "Hledám v kódu",
            "building": "Builduji",
            "archiving": "Archivuji",
            "uploading_testflight": "Nahrávám na TestFlight",
            "installing_deps": "Instaluji závislosti",
            "running_tests": "Spouštím testy",
            "committing": "Commituji změny",
            "pushing": "Pushuji na remote",
            "reading_web": "Čtu webovou stránku",
        ],
        "en": [
            "thinking": "Thinking",
            "understanding": "Got it, working",
            "analyzing": "Analyzing",
            "reading_file": "Reading file",
            "writing_file": "Writing file",
            "writing_code": "Writing code",
            "editing_code": "Editing code",
            "running_command": "Running command",
            "searching_web": "Searching the web",
            "searching_contact": "Looking up contact",
            "searching_restaurant": "Finding a restaurant",
            "searching_calendar": "Checking calendar",
            "calling_api": "Calling service",
            "processing_image": "Processing image",
            "generating_response": "Forming response",
            "composing": "Composing reply",
            "explaining": "Explaining",
            "recommending": "Preparing recommendation",
            "comparing": "Comparing options",
            "listing_steps": "Listing steps",
            "summarizing": "Summarizing",
            "warning": "Flagging risks",
            "finishing": "Finishing up",
            "needs_confirmation": "Needs confirmation",
            "saving": "Saving changes",
            "browsing_results": "Browsing results",
            "searching_deeper": "Searching deeper",
            "preparing_report": "Preparing report",
            "fetching_news": "Fetching news",
            "analyzing_news": "Analyzing articles",
            "checking_weather": "Checking weather",
            "searching_wiki": "Searching Wikipedia",
            "checking_exchange": "Checking exchange rates",
            "searching_cinema": "Searching cinemas",
            "searching_places": "Searching places",
            "reading_email": "Reading emails",
            "adding_calendar": "Adding to calendar",
            "searching_files": "Browsing files",
            "searching_code": "Searching code",
            "building": "Building",
            "archiving": "Archiving",
            "uploading_testflight": "Uploading to TestFlight",
            "installing_deps": "Installing dependencies",
            "running_tests": "Running tests",
            "committing": "Committing changes",
            "pushing": "Pushing to remote",
            "reading_web": "Reading web page",
        ],
        "de": [
            "thinking": "Denke nach",
            "understanding": "Verstanden, arbeite",
            "analyzing": "Analysiere",
            "reading_file": "Lese Datei",
            "writing_file": "Schreibe Datei",
            "writing_code": "Schreibe Code",
            "editing_code": "Bearbeite Code",
            "running_command": "Führe Befehl aus",
            "searching_web": "Suche im Web",
            "searching_contact": "Suche Kontakt",
            "searching_restaurant": "Suche Restaurant",
            "searching_calendar": "Prüfe Kalender",
            "calling_api": "Rufe Dienst auf",
            "processing_image": "Verarbeite Bild",
            "generating_response": "Formuliere Antwort",
            "composing": "Verfasse Antwort",
            "explaining": "Erkläre",
            "recommending": "Bereite Empfehlung vor",
            "comparing": "Vergleiche Optionen",
            "listing_steps": "Erstelle Schritte",
            "summarizing": "Fasse zusammen",
            "warning": "Weise auf Risiken hin",
            "finishing": "Schließe ab",
            "needs_confirmation": "Bestätigung nötig",
            "saving": "Speichere Änderungen",
            "browsing_results": "Durchsuche Ergebnisse",
            "searching_deeper": "Suche gründlicher",
            "preparing_report": "Erstelle Bericht",
            "fetching_news": "Lade Nachrichten",
            "analyzing_news": "Analysiere Artikel",
            "checking_weather": "Prüfe Wetter",
            "searching_wiki": "Suche auf Wikipedia",
            "checking_exchange": "Prüfe Wechselkurse",
            "searching_cinema": "Suche Kinoprogramm",
            "searching_places": "Suche Orte",
            "reading_email": "Lese E-Mails",
            "adding_calendar": "Trage in Kalender ein",
            "searching_files": "Durchsuche Dateien",
            "searching_code": "Suche im Code",
            "building": "Baue", "archiving": "Archiviere",
            "uploading_testflight": "Lade auf TestFlight hoch",
            "installing_deps": "Installiere Abhängigkeiten",
            "running_tests": "Führe Tests aus",
            "committing": "Committe Änderungen", "pushing": "Pushe zum Remote",
        ],
        "fr": [
            "thinking": "Je réfléchis",
            "understanding": "Compris, je travaille",
            "analyzing": "J'analyse",
            "reading_file": "Lecture du fichier",
            "writing_file": "Écriture du fichier",
            "writing_code": "Écriture du code",
            "editing_code": "Modification du code",
            "running_command": "Exécution de la commande",
            "searching_web": "Recherche sur le web",
            "searching_contact": "Recherche du contact",
            "searching_restaurant": "Recherche de restaurant",
            "searching_calendar": "Consultation du calendrier",
            "calling_api": "Appel du service",
            "processing_image": "Traitement de l'image",
            "generating_response": "Formulation de la réponse",
            "composing": "Rédaction de la réponse",
            "explaining": "J'explique",
            "recommending": "Préparation des recommandations",
            "comparing": "Comparaison des options",
            "listing_steps": "Établissement des étapes",
            "summarizing": "Résumé",
            "warning": "Signalement des risques",
            "finishing": "Finalisation",
            "needs_confirmation": "Confirmation requise",
            "saving": "Enregistrement des modifications",
            "browsing_results": "Parcours des résultats",
            "searching_deeper": "Recherche approfondie",
            "preparing_report": "Préparation du rapport",
            "fetching_news": "Téléchargement des actualités",
            "analyzing_news": "Analyse des articles",
            "checking_weather": "Consultation de la météo",
            "searching_wiki": "Recherche sur Wikipédia",
            "checking_exchange": "Consultation des taux de change",
            "searching_cinema": "Recherche du programme cinéma",
            "searching_places": "Recherche de lieux",
            "reading_email": "Lecture des e-mails",
            "adding_calendar": "Ajout au calendrier",
            "searching_files": "Parcours des fichiers",
            "searching_code": "Recherche dans le code",
            "building": "Compilation", "archiving": "Archivage",
            "uploading_testflight": "Envoi sur TestFlight",
            "installing_deps": "Installation des dépendances",
            "running_tests": "Exécution des tests",
            "committing": "Commit des modifications", "pushing": "Push vers le remote",
        ],
        "es": [
            "thinking": "Pensando",
            "understanding": "Entendido, trabajando",
            "analyzing": "Analizando",
            "reading_file": "Leyendo archivo",
            "writing_file": "Escribiendo archivo",
            "writing_code": "Escribiendo código",
            "editing_code": "Editando código",
            "running_command": "Ejecutando comando",
            "searching_web": "Buscando en la web",
            "searching_contact": "Buscando contacto",
            "searching_restaurant": "Buscando restaurante",
            "searching_calendar": "Consultando calendario",
            "calling_api": "Llamando al servicio",
            "processing_image": "Procesando imagen",
            "generating_response": "Formulando respuesta",
            "composing": "Componiendo respuesta",
            "explaining": "Explicando",
            "recommending": "Preparando recomendación",
            "comparing": "Comparando opciones",
            "listing_steps": "Listando pasos",
            "summarizing": "Resumiendo",
            "warning": "Señalando riesgos",
            "finishing": "Finalizando",
            "needs_confirmation": "Necesita confirmación",
            "saving": "Guardando cambios",
            "browsing_results": "Revisando resultados",
            "searching_deeper": "Buscando más a fondo",
            "preparing_report": "Preparando informe",
            "fetching_news": "Descargando noticias",
            "analyzing_news": "Analizando artículos",
            "checking_weather": "Consultando el clima",
            "searching_wiki": "Buscando en Wikipedia",
            "checking_exchange": "Consultando tipos de cambio",
            "searching_cinema": "Buscando cartelera",
            "searching_places": "Buscando lugares",
            "reading_email": "Leyendo correos",
            "adding_calendar": "Agregando al calendario",
            "searching_files": "Buscando archivos",
            "searching_code": "Buscando en el código",
            "building": "Compilando", "archiving": "Archivando",
            "uploading_testflight": "Subiendo a TestFlight",
            "installing_deps": "Instalando dependencias",
            "running_tests": "Ejecutando pruebas",
            "committing": "Haciendo commit", "pushing": "Haciendo push",
        ],
        "ja": [
            "thinking": "考え中",
            "understanding": "了解、作業中",
            "analyzing": "分析中",
            "reading_file": "ファイルを読み込み中",
            "writing_file": "ファイルを書き込み中",
            "writing_code": "コードを作成中",
            "editing_code": "コードを編集中",
            "running_command": "コマンドを実行中",
            "searching_web": "ウェブを検索中",
            "searching_contact": "連絡先を検索中",
            "searching_restaurant": "レストランを検索中",
            "searching_calendar": "カレンダーを確認中",
            "calling_api": "サービスを呼び出し中",
            "processing_image": "画像を処理中",
            "generating_response": "返答を構成中",
            "composing": "返答を作成中",
            "explaining": "説明中",
            "recommending": "推奨を準備中",
            "comparing": "選択肢を比較中",
            "listing_steps": "手順を整理中",
            "summarizing": "まとめ中",
            "warning": "リスクを指摘中",
            "finishing": "完了中",
            "needs_confirmation": "確認が必要",
            "saving": "変更を保存中",
            "browsing_results": "結果を閲覧中",
            "searching_deeper": "詳細検索中",
            "preparing_report": "レポートを作成中",
            "fetching_news": "ニュースを取得中",
            "analyzing_news": "記事を分析中",
            "checking_weather": "天気を確認中",
            "searching_wiki": "Wikipediaで検索中",
            "checking_exchange": "為替レートを確認中",
            "searching_cinema": "映画館を検索中",
            "searching_places": "場所を検索中",
            "reading_email": "メールを読み込み中",
            "adding_calendar": "カレンダーに追加中",
            "searching_files": "ファイルを検索中",
            "searching_code": "コード内を検索中",
            "building": "ビルド中", "archiving": "アーカイブ中",
            "uploading_testflight": "TestFlightにアップロード中",
            "installing_deps": "依存関係をインストール中",
            "running_tests": "テストを実行中",
            "committing": "コミット中", "pushing": "プッシュ中",
        ],
        "zh": [
            "thinking": "思考中",
            "understanding": "收到，处理中",
            "analyzing": "分析中",
            "reading_file": "正在读取文件",
            "writing_file": "正在写入文件",
            "writing_code": "正在编写代码",
            "editing_code": "正在编辑代码",
            "running_command": "正在执行命令",
            "searching_web": "正在搜索网络",
            "searching_contact": "正在查找联系人",
            "searching_restaurant": "正在查找餐厅",
            "searching_calendar": "正在查看日历",
            "calling_api": "正在调用服务",
            "processing_image": "正在处理图片",
            "generating_response": "正在组织回复",
            "composing": "正在撰写回复",
            "explaining": "正在解释",
            "recommending": "正在准备建议",
            "comparing": "正在比较选项",
            "listing_steps": "正在列出步骤",
            "summarizing": "正在总结",
            "warning": "正在提示风险",
            "finishing": "即将完成",
            "needs_confirmation": "需要确认",
            "saving": "正在保存更改",
            "browsing_results": "正在浏览结果",
            "searching_deeper": "正在深入搜索",
            "preparing_report": "正在准备报告",
            "fetching_news": "正在获取新闻",
            "analyzing_news": "正在分析文章",
            "checking_weather": "正在查看天气",
            "searching_wiki": "正在搜索维基百科",
            "checking_exchange": "正在查看汇率",
            "searching_cinema": "正在搜索电影院",
            "searching_places": "正在搜索地点",
            "reading_email": "正在阅读邮件",
            "adding_calendar": "正在添加到日历",
            "searching_files": "正在浏览文件",
            "searching_code": "正在搜索代码",
            "building": "正在构建", "archiving": "正在归档",
            "uploading_testflight": "正在上传到TestFlight",
            "installing_deps": "正在安装依赖",
            "running_tests": "正在运行测试",
            "committing": "正在提交更改", "pushing": "正在推送到远程",
        ],
    ]

    /// Return name in vocative case for current language.
    /// - Czech: applies heuristic declension rules covering ~80% of common names.
    /// - Other languages: returns name unchanged (Hello Mark, Hello Anna).
    static func vocative(_ name: String) -> String {
        let trimmed = name.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else { return trimmed }
        guard current == "cs" else { return trimmed }
        return czechVocative(trimmed)
    }

    private static func czechVocative(_ name: String) -> String {
        let lower = name.lowercased()
        // Irregular / exceptions (lowercase match)
        let exceptions: [String: String] = [
            "petr": "Petře", "pavel": "Pavle", "karel": "Karle",
            "bůh": "Bože", "otec": "Otče", "syn": "Synu",
            "ježíš": "Ježíši", "ondřej": "Ondřeji", "jiří": "Jiří",
            "matěj": "Matěji", "tomáš": "Tomáši", "lukáš": "Lukáši",
            "aleš": "Aleši", "jakub": "Jakube", "martin": "Martine",
            "david": "Davide", "adam": "Adame", "michal": "Michale",
            "honza": "Honzo", "jan": "Jane", "filip": "Filipe",
            "štěpán": "Štěpáne", "marek": "Marku", "radek": "Radku",
            "patrik": "Patriku", "vojtěch": "Vojtěchu", "roman": "Romane",
            "robert": "Roberte", "daniel": "Danieli", "dominik": "Dominiku",
            "ivan": "Ivane", "igor": "Igore", "josef": "Josefe",
        ]
        if let fixed = exceptions[lower] { return fixed }

        // Female name ending in -a → -o (Monika → Moniko, Jana → Jano)
        if lower.hasSuffix("a") {
            return String(name.dropLast()) + "o"
        }
        // -ie / -ia → unchanged (Marie, Sofia)
        if lower.hasSuffix("ie") || lower.hasSuffix("ia") {
            return name
        }
        // Male -ej / -aj / -oj → add -i (Ondřej → Ondřeji, fallback if not in exceptions)
        if lower.hasSuffix("ej") || lower.hasSuffix("aj") || lower.hasSuffix("oj") {
            return name + "i"
        }
        // Male ending in soft consonant (č, š, ž, ř, j, ť, ď, ň, c) → -i
        let lastChar = lower.last!
        let softConsonants: Set<Character> = ["č", "š", "ž", "ř", "j", "c"]
        if softConsonants.contains(lastChar) {
            return name + "i"
        }
        // Ending in -l → -le (Pavel handled, fallback)
        if lower.hasSuffix("el") {
            return String(name.dropLast(2)) + "le"
        }
        // Default: male hard consonant → -e
        return name + "e"
    }

    static func stage(_ key: String?, detail: String? = nil) -> String {
        let lang = current
        let resolvedKey = key ?? "thinking"
        let label = stages[lang]?[resolvedKey] ?? stages["en"]?[resolvedKey] ?? stages["en"]?["thinking"] ?? "Thinking"
        if let detail = detail, !detail.isEmpty {
            // Prémiový formát: "Čtu soubor (ContentView.swift)" místo "Čtu soubor: ContentView.swift"
            return "\(label)  ·  \(detail)"
        }
        return label
    }
}
