import Foundation

struct L10n {
    static var current: String {
        UserDefaults.standard.string(forKey: "nova_lang") ?? "cs"
    }

    static let strings: [String: [String: String]] = [
        "cs": [
            "settings": "Nastavení", "save": "Uložit", "name": "Jméno", "cancel": "Zrušit",
            "personal_ai": "Tvoje osobní AI asistentka", "mac_server_info": "Tvůj Mac server běží Claude Code",
            "speak_now": "Mluvte...", "welcome_nova": "Vítej v Nově", "token_label": "Bezpečnostní token",
            "setup_desc": "Zadej adresu svého Mac serveru a bezpečnostní token pro připojení.",
            "name_placeholder": "Tvoje jméno", "city": "Domovské město",
            "city_placeholder": "Město", "language": "Jazyk",
            "voice": "Hlas asistenta", "female": "Ženský", "male": "Mužský",
            "connection": "Připojení", "connected": "Připojeno", "disconnected": "Odpojeno",
            "change_server": "Změnit server", "ready": "Připravena",
            "listening": "Poslouchám...", "thinking": "Přemýšlím...", "speaking": "Mluvím...",
            "write_nova": "Napiš Nově...", "you": "Ty", "send": "Odeslat",
            "connect": "Připojit", "server_title": "Připojení k serveru",
            "speech_recognition": "Rozpoznávání řeči", "stt_connected": "Připojeno",
            "stt_loading": "Načítám model...", "stt_error": "Chyba načtení", "stt_offline": "Nepřipojeno",
            "stt_desc": "WhisperKit on-device, auto-detect jazyka",
            "voice_id": "Voice ID", "voice_profile_active": "Hlasový profil aktivní",
            "voice_profile_none": "Hlasový profil nevytvořen",
            "voice_responds_you": "Nova reaguje jen na tebe", "face_id_voice": "Face ID pro tvůj hlas",
            "create_profile": "Vytvořit profil", "manage_profile": "Spravovat profil",
            "require_verification": "Vyžadovat ověření hlasu",
            "verify_on": "Nova reaguje jen pokud poznám tvůj hlas",
            "verify_off": "Nova reaguje na všechny mluvčí",
            "verification_strict": "Přísnost ověření", "last_match": "Poslední shoda",
            "permissive": "Permisivní", "balanced": "Vyvážené", "strict": "Přísné",
            "quick_actions": "Rychlé akce", "quick_actions_desc": "Tlačítka v hlavním chatu — tap = okamžitá akce",
            "action_name": "Název", "action_prompt": "Co říct Nově...", "add_action": "Přidat akci",
            "about": "O aplikaci", "version": "Verze", "developer": "Vývojář",
            "delete_history": "Smazat historii", "delete_history_confirm": "Smazat historii?",
            "delete_history_msg": "Tato akce je nevratná. Všechny zprávy v konverzaci budou smazány.",
            "delete": "Smazat", "what_today": "Co dnes potřebuješ?",
            "voice_unrecognized": "Hlas nepoznán",
            "dev_project": "Dev projekt",
        ],
        "en": [
            "settings": "Settings", "save": "Save", "name": "Name", "cancel": "Cancel",
            "personal_ai": "Your personal AI assistant", "mac_server_info": "Your Mac server runs Claude Code",
            "speak_now": "Speak...", "welcome_nova": "Welcome to Nova", "token_label": "Security token",
            "setup_desc": "Enter your Mac server address and security token to connect.",
            "name_placeholder": "Your name", "city": "Home city",
            "city_placeholder": "City", "language": "Language",
            "voice": "Assistant voice", "female": "Female", "male": "Male",
            "connection": "Connection", "connected": "Connected", "disconnected": "Disconnected",
            "change_server": "Change server", "ready": "Ready",
            "listening": "Listening...", "thinking": "Thinking...", "speaking": "Speaking...",
            "write_nova": "Write to Nova...", "you": "You", "send": "Send",
            "connect": "Connect", "server_title": "Connect to server",
            "speech_recognition": "Speech Recognition", "stt_connected": "Connected",
            "stt_loading": "Loading model...", "stt_error": "Load error", "stt_offline": "Offline",
            "stt_desc": "WhisperKit on-device, auto language detection",
            "voice_id": "Voice ID", "voice_profile_active": "Voice profile active",
            "voice_profile_none": "Voice profile not created",
            "voice_responds_you": "Nova responds only to you", "face_id_voice": "Face ID for your voice",
            "create_profile": "Create profile", "manage_profile": "Manage profile",
            "require_verification": "Require voice verification",
            "verify_on": "Nova responds only when your voice is recognized",
            "verify_off": "Nova responds to all speakers",
            "verification_strict": "Verification strictness", "last_match": "Last match",
            "permissive": "Permissive", "balanced": "Balanced", "strict": "Strict",
            "quick_actions": "Quick Actions", "quick_actions_desc": "Buttons in main chat — tap for instant action",
            "action_name": "Name", "action_prompt": "What to tell Nova...", "add_action": "Add action",
            "about": "About", "version": "Version", "developer": "Developer",
            "delete_history": "Delete history", "delete_history_confirm": "Delete history?",
            "delete_history_msg": "This action cannot be undone. All messages will be deleted.",
            "delete": "Delete", "what_today": "What do you need today?",
            "voice_unrecognized": "Voice not recognized",
            "dev_project": "Dev project",
        ],
        "de": [
            "settings": "Einstellungen", "save": "Speichern", "name": "Name", "cancel": "Abbrechen",
            "personal_ai": "Dein persönlicher KI-Assistent", "mac_server_info": "Dein Mac-Server läuft mit Claude Code",
            "speak_now": "Sprechen...", "welcome_nova": "Willkommen bei Nova", "token_label": "Sicherheitstoken",
            "setup_desc": "Gib die Adresse deines Mac-Servers und den Sicherheitstoken ein.",
            "name_placeholder": "Dein Name", "city": "Heimatstadt",
            "city_placeholder": "Stadt", "language": "Sprache",
            "voice": "Assistentenstimme", "female": "Weiblich", "male": "Männlich",
            "connection": "Verbindung", "connected": "Verbunden", "disconnected": "Getrennt",
            "change_server": "Server ändern", "ready": "Bereit",
            "listening": "Höre zu...", "thinking": "Denke nach...", "speaking": "Spreche...",
            "write_nova": "Schreib Nova...", "you": "Du", "send": "Senden",
            "connect": "Verbinden", "server_title": "Mit Server verbinden",
            "speech_recognition": "Spracherkennung", "stt_connected": "Verbunden",
            "stt_loading": "Modell laden...", "stt_error": "Ladefehler", "stt_offline": "Offline",
            "stt_desc": "WhisperKit on-device, automatische Spracherkennung",
            "voice_id": "Voice ID", "voice_profile_active": "Stimmprofil aktiv",
            "voice_profile_none": "Kein Stimmprofil erstellt",
            "voice_responds_you": "Nova reagiert nur auf dich", "face_id_voice": "Face ID für deine Stimme",
            "create_profile": "Profil erstellen", "manage_profile": "Profil verwalten",
            "require_verification": "Stimmverifizierung erforderlich",
            "verify_on": "Nova reagiert nur bei erkannter Stimme",
            "verify_off": "Nova reagiert auf alle Sprecher",
            "verification_strict": "Verifizierungsstrenge", "last_match": "Letzte Übereinstimmung",
            "permissive": "Tolerant", "balanced": "Ausgewogen", "strict": "Streng",
            "quick_actions": "Schnellaktionen", "quick_actions_desc": "Buttons im Chat — tippen für sofortige Aktion",
            "action_name": "Name", "action_prompt": "Was Nova sagen...", "add_action": "Aktion hinzufügen",
            "about": "Über die App", "version": "Version", "developer": "Entwickler",
            "delete_history": "Verlauf löschen", "delete_history_confirm": "Verlauf löschen?",
            "delete_history_msg": "Diese Aktion kann nicht rückgängig gemacht werden.",
            "delete": "Löschen", "what_today": "Was brauchst du heute?",
            "voice_unrecognized": "Stimme nicht erkannt",
            "dev_project": "Dev-Projekt",
        ],
        "fr": [
            "settings": "Paramètres", "save": "Enregistrer", "name": "Nom", "cancel": "Annuler",
            "personal_ai": "Ton assistant IA personnel", "mac_server_info": "Ton serveur Mac utilise Claude Code",
            "speak_now": "Parle...", "welcome_nova": "Bienvenue sur Nova", "token_label": "Jeton de sécurité",
            "setup_desc": "Entre l'adresse de ton serveur Mac et le jeton de sécurité.",
            "name_placeholder": "Ton nom", "city": "Ville",
            "city_placeholder": "Ville", "language": "Langue",
            "voice": "Voix de l'assistant", "female": "Féminine", "male": "Masculine",
            "connection": "Connexion", "connected": "Connecté", "disconnected": "Déconnecté",
            "change_server": "Changer de serveur", "ready": "Prête",
            "listening": "J'écoute...", "thinking": "Je réfléchis...", "speaking": "Je parle...",
            "write_nova": "Écris à Nova...", "you": "Toi", "send": "Envoyer",
            "connect": "Connecter", "server_title": "Connexion au serveur",
            "speech_recognition": "Reconnaissance vocale", "stt_connected": "Connecté",
            "stt_loading": "Chargement du modèle...", "stt_error": "Erreur de chargement", "stt_offline": "Hors ligne",
            "stt_desc": "WhisperKit on-device, détection automatique de la langue",
            "voice_id": "Voice ID", "voice_profile_active": "Profil vocal actif",
            "voice_profile_none": "Profil vocal non créé",
            "voice_responds_you": "Nova ne répond qu'à toi", "face_id_voice": "Face ID pour ta voix",
            "create_profile": "Créer un profil", "manage_profile": "Gérer le profil",
            "require_verification": "Exiger la vérification vocale",
            "verify_on": "Nova ne répond que si ta voix est reconnue",
            "verify_off": "Nova répond à tous les interlocuteurs",
            "verification_strict": "Rigueur de vérification", "last_match": "Dernière correspondance",
            "permissive": "Permissif", "balanced": "Équilibré", "strict": "Strict",
            "quick_actions": "Actions rapides", "quick_actions_desc": "Boutons dans le chat — appui pour action instantanée",
            "action_name": "Nom", "action_prompt": "Que dire à Nova...", "add_action": "Ajouter une action",
            "about": "À propos", "version": "Version", "developer": "Développeur",
            "delete_history": "Supprimer l'historique", "delete_history_confirm": "Supprimer l'historique?",
            "delete_history_msg": "Cette action est irréversible. Tous les messages seront supprimés.",
            "delete": "Supprimer", "what_today": "De quoi as-tu besoin aujourd'hui?",
            "voice_unrecognized": "Voix non reconnue",
            "dev_project": "Projet dev",
        ],
        "es": [
            "settings": "Ajustes", "save": "Guardar", "name": "Nombre", "cancel": "Cancelar",
            "personal_ai": "Tu asistente IA personal", "mac_server_info": "Tu servidor Mac ejecuta Claude Code",
            "speak_now": "Habla...", "welcome_nova": "Bienvenido a Nova", "token_label": "Token de seguridad",
            "setup_desc": "Ingresa la dirección de tu servidor Mac y el token de seguridad.",
            "name_placeholder": "Tu nombre", "city": "Ciudad",
            "city_placeholder": "Ciudad", "language": "Idioma",
            "voice": "Voz del asistente", "female": "Femenina", "male": "Masculina",
            "connection": "Conexión", "connected": "Conectado", "disconnected": "Desconectado",
            "change_server": "Cambiar servidor", "ready": "Lista",
            "listening": "Escuchando...", "thinking": "Pensando...", "speaking": "Hablando...",
            "write_nova": "Escribe a Nova...", "you": "Tú", "send": "Enviar",
            "connect": "Conectar", "server_title": "Conexión al servidor",
            "speech_recognition": "Reconocimiento de voz", "stt_connected": "Conectado",
            "stt_loading": "Cargando modelo...", "stt_error": "Error de carga", "stt_offline": "Sin conexión",
            "stt_desc": "WhisperKit on-device, detección automática de idioma",
            "voice_id": "Voice ID", "voice_profile_active": "Perfil de voz activo",
            "voice_profile_none": "Perfil de voz no creado",
            "voice_responds_you": "Nova responde solo a ti", "face_id_voice": "Face ID para tu voz",
            "create_profile": "Crear perfil", "manage_profile": "Gestionar perfil",
            "require_verification": "Requerir verificación de voz",
            "verify_on": "Nova responde solo cuando reconoce tu voz",
            "verify_off": "Nova responde a todos",
            "verification_strict": "Rigurosidad", "last_match": "Última coincidencia",
            "permissive": "Permisivo", "balanced": "Equilibrado", "strict": "Estricto",
            "quick_actions": "Acciones rápidas", "quick_actions_desc": "Botones en el chat — toca para acción instantánea",
            "action_name": "Nombre", "action_prompt": "Qué decirle a Nova...", "add_action": "Añadir acción",
            "about": "Acerca de", "version": "Versión", "developer": "Desarrollador",
            "delete_history": "Borrar historial", "delete_history_confirm": "¿Borrar historial?",
            "delete_history_msg": "Esta acción no se puede deshacer. Todos los mensajes se eliminarán.",
            "delete": "Borrar", "what_today": "¿Qué necesitas hoy?",
            "voice_unrecognized": "Voz no reconocida",
            "dev_project": "Proyecto dev",
        ],
        "ja": [
            "settings": "設定", "save": "保存", "name": "名前", "cancel": "キャンセル",
            "name_placeholder": "あなたの名前", "city": "ホームシティ",
            "city_placeholder": "都市", "language": "言語",
            "voice": "アシスタントの声", "female": "女性", "male": "男性",
            "connection": "接続", "connected": "接続済み", "disconnected": "未接続",
            "change_server": "サーバー変更", "ready": "準備完了",
            "listening": "聞いています...", "thinking": "考えています...", "speaking": "話しています...",
            "write_nova": "Novaに書く...", "you": "あなた", "send": "送信",
            "connect": "接続", "server_title": "サーバーに接続",
            "speech_recognition": "音声認識", "stt_connected": "接続済み",
            "stt_loading": "モデル読込中...", "stt_error": "読込エラー", "stt_offline": "オフライン",
            "stt_desc": "WhisperKit オンデバイス、言語自動検出",
            "voice_id": "Voice ID", "voice_profile_active": "音声プロファイル有効",
            "voice_profile_none": "音声プロファイル未作成",
            "voice_responds_you": "Novaはあなただけに応答します", "face_id_voice": "声のFace ID",
            "create_profile": "プロファイル作成", "manage_profile": "プロファイル管理",
            "require_verification": "音声認証を要求",
            "verify_on": "声が認識された時のみ応答",
            "verify_off": "全ての話者に応答",
            "verification_strict": "認証厳格度", "last_match": "最後の一致",
            "permissive": "寛容", "balanced": "バランス", "strict": "厳格",
            "quick_actions": "クイックアクション", "quick_actions_desc": "チャットのボタン — タップで即時実行",
            "action_name": "名前", "action_prompt": "Novaに伝えること...", "add_action": "アクション追加",
            "about": "アプリについて", "version": "バージョン", "developer": "開発者",
            "delete_history": "履歴削除", "delete_history_confirm": "履歴を削除しますか？",
            "delete_history_msg": "この操作は元に戻せません。すべてのメッセージが削除されます。",
            "delete": "削除", "what_today": "今日は何が必要ですか？",
            "voice_unrecognized": "声が認識されません",
            "dev_project": "開発プロジェクト",
        ],
        "zh": [
            "settings": "设置", "save": "保存", "name": "姓名", "cancel": "取消",
            "name_placeholder": "你的名字", "city": "所在城市",
            "city_placeholder": "城市", "language": "语言",
            "voice": "助手语音", "female": "女声", "male": "男声",
            "connection": "连接", "connected": "已连接", "disconnected": "未连接",
            "change_server": "更改服务器", "ready": "就绪",
            "listening": "聆听中...", "thinking": "思考中...", "speaking": "说话中...",
            "write_nova": "写给Nova...", "you": "你", "send": "发送",
            "connect": "连接", "server_title": "连接到服务器",
            "speech_recognition": "语音识别", "stt_connected": "已连接",
            "stt_loading": "加载模型中...", "stt_error": "加载错误", "stt_offline": "离线",
            "stt_desc": "WhisperKit 本地运行，自动语言检测",
            "voice_id": "Voice ID", "voice_profile_active": "声纹已激活",
            "voice_profile_none": "声纹未创建",
            "voice_responds_you": "Nova只回应你", "face_id_voice": "语音Face ID",
            "create_profile": "创建声纹", "manage_profile": "管理声纹",
            "require_verification": "要求语音验证",
            "verify_on": "仅在识别你的声音时回应",
            "verify_off": "回应所有说话者",
            "verification_strict": "验证严格度", "last_match": "最后匹配",
            "permissive": "宽松", "balanced": "平衡", "strict": "严格",
            "quick_actions": "快捷操作", "quick_actions_desc": "聊天中的按钮 — 点击即时执行",
            "action_name": "名称", "action_prompt": "对Nova说...", "add_action": "添加操作",
            "about": "关于", "version": "版本", "developer": "开发者",
            "delete_history": "删除历史", "delete_history_confirm": "删除历史？",
            "delete_history_msg": "此操作不可撤销。所有消息将被删除。",
            "delete": "删除", "what_today": "今天需要什么？",
            "voice_unrecognized": "声音未识别",
            "dev_project": "开发项目",
        ],
    ]

    static func t(_ key: String) -> String {
        strings[current]?[key] ?? strings["en"]?[key] ?? key
    }

    // MARK: - Thinking stages (granular progress)
    static let stages: [String: [String: String]] = [
        "cs": [
            "thinking": "Přemýšlím",
            "understanding": "Rozumím, pracuji",
            "analyzing": "Analyzuji",
            "reading_file": "Čtu soubor",
            "writing_file": "Píšu do souboru",
            "writing_code": "Píšu kód",
            "editing_code": "Upravuji kód",
            "running_command": "Spouštím příkaz",
            "searching_web": "Hledám na webu",
            "searching_contact": "Hledám kontakt",
            "searching_restaurant": "Hledám restauraci",
            "searching_calendar": "Hledám v kalendáři",
            "calling_api": "Volám službu",
            "processing_image": "Zpracovávám obrázek",
            "generating_response": "Formuluji odpověď",
            "composing": "Skládám odpověď",
            "explaining": "Vysvětluji",
            "recommending": "Připravuji doporučení",
            "comparing": "Porovnávám možnosti",
            "listing_steps": "Sestavuji postup",
            "summarizing": "Shrnuji",
            "warning": "Upozorňuji na rizika",
            "finishing": "Dokončuji",
            "needs_confirmation": "Potřebuji souhlas",
            "saving": "Ukládám změny",
            "browsing_results": "Procházím výsledky",
            "searching_deeper": "Hledám podrobněji",
            "preparing_report": "Připravuji report",
            "fetching_news": "Stahuji zprávy",
            "analyzing_news": "Analyzuji zprávy",
            "checking_weather": "Zjišťuji počasí",
            "searching_wiki": "Hledám na Wikipedii",
            "checking_exchange": "Zjišťuji kurzy",
            "searching_cinema": "Hledám program kin",
            "searching_places": "Hledám místa",
            "reading_email": "Čtu emaily",
            "adding_calendar": "Zapisuji do kalendáře",
            "searching_files": "Procházím soubory",
            "searching_code": "Hledám v kódu",
            "building": "Builduji",
            "archiving": "Archivuji",
            "uploading_testflight": "Nahrávám na TestFlight",
            "installing_deps": "Instaluji závislosti",
            "running_tests": "Spouštím testy",
            "committing": "Commituji změny",
            "pushing": "Pushuji na remote",
            "reading_web": "Čtu webovou stránku",
        ],
        "en": [
            "thinking": "Thinking",
            "understanding": "Got it, working",
            "analyzing": "Analyzing",
            "reading_file": "Reading file",
            "writing_file": "Writing file",
            "writing_code": "Writing code",
            "editing_code": "Editing code",
            "running_command": "Running command",
            "searching_web": "Searching the web",
            "searching_contact": "Looking up contact",
            "searching_restaurant": "Finding a restaurant",
            "searching_calendar": "Checking calendar",
            "calling_api": "Calling service",
            "processing_image": "Processing image",
            "generating_response": "Forming response",
            "composing": "Composing reply",
            "explaining": "Explaining",
            "recommending": "Preparing recommendation",
            "comparing": "Comparing options",
            "listing_steps": "Listing steps",
            "summarizing": "Summarizing",
            "warning": "Flagging risks",
            "finishing": "Finishing up",
            "needs_confirmation": "Needs confirmation",
            "saving": "Saving changes",
            "browsing_results": "Browsing results",
            "searching_deeper": "Searching deeper",
            "preparing_report": "Preparing report",
            "fetching_news": "Fetching news",
            "analyzing_news": "Analyzing articles",
            "checking_weather": "Checking weather",
            "searching_wiki": "Searching Wikipedia",
            "checking_exchange": "Checking exchange rates",
            "searching_cinema": "Searching cinemas",
            "searching_places": "Searching places",
            "reading_email": "Reading emails",
            "adding_calendar": "Adding to calendar",
            "searching_files": "Browsing files",
            "searching_code": "Searching code",
            "building": "Building",
            "archiving": "Archiving",
            "uploading_testflight": "Uploading to TestFlight",
            "installing_deps": "Installing dependencies",
            "running_tests": "Running tests",
            "committing": "Committing changes",
            "pushing": "Pushing to remote",
            "reading_web": "Reading web page",
        ],
        "de": [
            "thinking": "Denke nach",
            "understanding": "Verstanden, arbeite",
            "analyzing": "Analysiere",
            "reading_file": "Lese Datei",
            "writing_file": "Schreibe Datei",
            "writing_code": "Schreibe Code",
            "editing_code": "Bearbeite Code",
            "running_command": "Führe Befehl aus",
            "searching_web": "Suche im Web",
            "searching_contact": "Suche Kontakt",
            "searching_restaurant": "Suche Restaurant",
            "searching_calendar": "Prüfe Kalender",
            "calling_api": "Rufe Dienst auf",
            "processing_image": "Verarbeite Bild",
            "generating_response": "Formuliere Antwort",
            "composing": "Verfasse Antwort",
            "explaining": "Erkläre",
            "recommending": "Bereite Empfehlung vor",
            "comparing": "Vergleiche Optionen",
            "listing_steps": "Erstelle Schritte",
            "summarizing": "Fasse zusammen",
            "warning": "Weise auf Risiken hin",
            "finishing": "Schließe ab",
            "needs_confirmation": "Bestätigung nötig",
            "saving": "Speichere Änderungen",
            "browsing_results": "Durchsuche Ergebnisse",
            "searching_deeper": "Suche gründlicher",
            "preparing_report": "Erstelle Bericht",
            "fetching_news": "Lade Nachrichten",
            "analyzing_news": "Analysiere Artikel",
            "checking_weather": "Prüfe Wetter",
            "searching_wiki": "Suche auf Wikipedia",
            "checking_exchange": "Prüfe Wechselkurse",
            "searching_cinema": "Suche Kinoprogramm",
            "searching_places": "Suche Orte",
            "reading_email": "Lese E-Mails",
            "adding_calendar": "Trage in Kalender ein",
            "searching_files": "Durchsuche Dateien",
            "searching_code": "Suche im Code",
            "building": "Baue", "archiving": "Archiviere",
            "uploading_testflight": "Lade auf TestFlight hoch",
            "installing_deps": "Installiere Abhängigkeiten",
            "running_tests": "Führe Tests aus",
            "committing": "Committe Änderungen", "pushing": "Pushe zum Remote",
        ],
        "fr": [
            "thinking": "Je réfléchis",
            "understanding": "Compris, je travaille",
            "analyzing": "J'analyse",
            "reading_file": "Lecture du fichier",
            "writing_file": "Écriture du fichier",
            "writing_code": "Écriture du code",
            "editing_code": "Modification du code",
            "running_command": "Exécution de la commande",
            "searching_web": "Recherche sur le web",
            "searching_contact": "Recherche du contact",
            "searching_restaurant": "Recherche de restaurant",
            "searching_calendar": "Consultation du calendrier",
            "calling_api": "Appel du service",
            "processing_image": "Traitement de l'image",
            "generating_response": "Formulation de la réponse",
            "composing": "Rédaction de la réponse",
            "explaining": "J'explique",
            "recommending": "Préparation des recommandations",
            "comparing": "Comparaison des options",
            "listing_steps": "Établissement des étapes",
            "summarizing": "Résumé",
            "warning": "Signalement des risques",
            "finishing": "Finalisation",
            "needs_confirmation": "Confirmation requise",
            "saving": "Enregistrement des modifications",
            "browsing_results": "Parcours des résultats",
            "searching_deeper": "Recherche approfondie",
            "preparing_report": "Préparation du rapport",
            "fetching_news": "Téléchargement des actualités",
            "analyzing_news": "Analyse des articles",
            "checking_weather": "Consultation de la météo",
            "searching_wiki": "Recherche sur Wikipédia",
            "checking_exchange": "Consultation des taux de change",
            "searching_cinema": "Recherche du programme cinéma",
            "searching_places": "Recherche de lieux",
            "reading_email": "Lecture des e-mails",
            "adding_calendar": "Ajout au calendrier",
            "searching_files": "Parcours des fichiers",
            "searching_code": "Recherche dans le code",
            "building": "Compilation", "archiving": "Archivage",
            "uploading_testflight": "Envoi sur TestFlight",
            "installing_deps": "Installation des dépendances",
            "running_tests": "Exécution des tests",
            "committing": "Commit des modifications", "pushing": "Push vers le remote",
        ],
        "es": [
            "thinking": "Pensando",
            "understanding": "Entendido, trabajando",
            "analyzing": "Analizando",
            "reading_file": "Leyendo archivo",
            "writing_file": "Escribiendo archivo",
            "writing_code": "Escribiendo código",
            "editing_code": "Editando código",
            "running_command": "Ejecutando comando",
            "searching_web": "Buscando en la web",
            "searching_contact": "Buscando contacto",
            "searching_restaurant": "Buscando restaurante",
            "searching_calendar": "Consultando calendario",
            "calling_api": "Llamando al servicio",
            "processing_image": "Procesando imagen",
            "generating_response": "Formulando respuesta",
            "composing": "Componiendo respuesta",
            "explaining": "Explicando",
            "recommending": "Preparando recomendación",
            "comparing": "Comparando opciones",
            "listing_steps": "Listando pasos",
            "summarizing": "Resumiendo",
            "warning": "Señalando riesgos",
            "finishing": "Finalizando",
            "needs_confirmation": "Necesita confirmación",
            "saving": "Guardando cambios",
            "browsing_results": "Revisando resultados",
            "searching_deeper": "Buscando más a fondo",
            "preparing_report": "Preparando informe",
            "fetching_news": "Descargando noticias",
            "analyzing_news": "Analizando artículos",
            "checking_weather": "Consultando el clima",
            "searching_wiki": "Buscando en Wikipedia",
            "checking_exchange": "Consultando tipos de cambio",
            "searching_cinema": "Buscando cartelera",
            "searching_places": "Buscando lugares",
            "reading_email": "Leyendo correos",
            "adding_calendar": "Agregando al calendario",
            "searching_files": "Buscando archivos",
            "searching_code": "Buscando en el código",
            "building": "Compilando", "archiving": "Archivando",
            "uploading_testflight": "Subiendo a TestFlight",
            "installing_deps": "Instalando dependencias",
            "running_tests": "Ejecutando pruebas",
            "committing": "Haciendo commit", "pushing": "Haciendo push",
        ],
        "ja": [
            "thinking": "考え中",
            "understanding": "了解、作業中",
            "analyzing": "分析中",
            "reading_file": "ファイルを読み込み中",
            "writing_file": "ファイルを書き込み中",
            "writing_code": "コードを作成中",
            "editing_code": "コードを編集中",
            "running_command": "コマンドを実行中",
            "searching_web": "ウェブを検索中",
            "searching_contact": "連絡先を検索中",
            "searching_restaurant": "レストランを検索中",
            "searching_calendar": "カレンダーを確認中",
            "calling_api": "サービスを呼び出し中",
            "processing_image": "画像を処理中",
            "generating_response": "返答を構成中",
            "composing": "返答を作成中",
            "explaining": "説明中",
            "recommending": "推奨を準備中",
            "comparing": "選択肢を比較中",
            "listing_steps": "手順を整理中",
            "summarizing": "まとめ中",
            "warning": "リスクを指摘中",
            "finishing": "完了中",
            "needs_confirmation": "確認が必要",
            "saving": "変更を保存中",
            "browsing_results": "結果を閲覧中",
            "searching_deeper": "詳細検索中",
            "preparing_report": "レポートを作成中",
            "fetching_news": "ニュースを取得中",
            "analyzing_news": "記事を分析中",
            "checking_weather": "天気を確認中",
            "searching_wiki": "Wikipediaで検索中",
            "checking_exchange": "為替レートを確認中",
            "searching_cinema": "映画館を検索中",
            "searching_places": "場所を検索中",
            "reading_email": "メールを読み込み中",
            "adding_calendar": "カレンダーに追加中",
            "searching_files": "ファイルを検索中",
            "searching_code": "コード内を検索中",
            "building": "ビルド中", "archiving": "アーカイブ中",
            "uploading_testflight": "TestFlightにアップロード中",
            "installing_deps": "依存関係をインストール中",
            "running_tests": "テストを実行中",
            "committing": "コミット中", "pushing": "プッシュ中",
        ],
        "zh": [
            "thinking": "思考中",
            "understanding": "收到，处理中",
            "analyzing": "分析中",
            "reading_file": "正在读取文件",
            "writing_file": "正在写入文件",
            "writing_code": "正在编写代码",
            "editing_code": "正在编辑代码",
            "running_command": "正在执行命令",
            "searching_web": "正在搜索网络",
            "searching_contact": "正在查找联系人",
            "searching_restaurant": "正在查找餐厅",
            "searching_calendar": "正在查看日历",
            "calling_api": "正在调用服务",
            "processing_image": "正在处理图片",
            "generating_response": "正在组织回复",
            "composing": "正在撰写回复",
            "explaining": "正在解释",
            "recommending": "正在准备建议",
            "comparing": "正在比较选项",
            "listing_steps": "正在列出步骤",
            "summarizing": "正在总结",
            "warning": "正在提示风险",
            "finishing": "即将完成",
            "needs_confirmation": "需要确认",
            "saving": "正在保存更改",
            "browsing_results": "正在浏览结果",
            "searching_deeper": "正在深入搜索",
            "preparing_report": "正在准备报告",
            "fetching_news": "正在获取新闻",
            "analyzing_news": "正在分析文章",
            "checking_weather": "正在查看天气",
            "searching_wiki": "正在搜索维基百科",
            "checking_exchange": "正在查看汇率",
            "searching_cinema": "正在搜索电影院",
            "searching_places": "正在搜索地点",
            "reading_email": "正在阅读邮件",
            "adding_calendar": "正在添加到日历",
            "searching_files": "正在浏览文件",
            "searching_code": "正在搜索代码",
            "building": "正在构建", "archiving": "正在归档",
            "uploading_testflight": "正在上传到TestFlight",
            "installing_deps": "正在安装依赖",
            "running_tests": "正在运行测试",
            "committing": "正在提交更改", "pushing": "正在推送到远程",
        ],
    ]

    /// Return name in vocative case for current language.
    /// - Czech: applies heuristic declension rules covering ~80% of common names.
    /// - Other languages: returns name unchanged (Hello Mark, Hello Anna).
    static func vocative(_ name: String) -> String {
        let trimmed = name.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else { return trimmed }
        guard current == "cs" else { return trimmed }
        return czechVocative(trimmed)
    }

    private static func czechVocative(_ name: String) -> String {
        let lower = name.lowercased()
        // Irregular / exceptions (lowercase match)
        let exceptions: [String: String] = [
            "petr": "Petře", "pavel": "Pavle", "karel": "Karle",
            "bůh": "Bože", "otec": "Otče", "syn": "Synu",
            "ježíš": "Ježíši", "ondřej": "Ondřeji", "jiří": "Jiří",
            "matěj": "Matěji", "tomáš": "Tomáši", "lukáš": "Lukáši",
            "aleš": "Aleši", "jakub": "Jakube", "martin": "Martine",
            "david": "Davide", "adam": "Adame", "michal": "Michale",
            "honza": "Honzo", "jan": "Jane", "filip": "Filipe",
            "štěpán": "Štěpáne", "marek": "Marku", "radek": "Radku",
            "patrik": "Patriku", "vojtěch": "Vojtěchu", "roman": "Romane",
            "robert": "Roberte", "daniel": "Danieli", "dominik": "Dominiku",
            "ivan": "Ivane", "igor": "Igore", "josef": "Josefe",
        ]
        if let fixed = exceptions[lower] { return fixed }

        // Female name ending in -a → -o (Monika → Moniko, Jana → Jano)
        if lower.hasSuffix("a") {
            return String(name.dropLast()) + "o"
        }
        // -ie / -ia → unchanged (Marie, Sofia)
        if lower.hasSuffix("ie") || lower.hasSuffix("ia") {
            return name
        }
        // Male -ej / -aj / -oj → add -i (Ondřej → Ondřeji, fallback if not in exceptions)
        if lower.hasSuffix("ej") || lower.hasSuffix("aj") || lower.hasSuffix("oj") {
            return name + "i"
        }
        // Male ending in soft consonant (č, š, ž, ř, j, ť, ď, ň, c) → -i
        let lastChar = lower.last!
        let softConsonants: Set<Character> = ["č", "š", "ž", "ř", "j", "c"]
        if softConsonants.contains(lastChar) {
            return name + "i"
        }
        // Ending in -l → -le (Pavel handled, fallback)
        if lower.hasSuffix("el") {
            return String(name.dropLast(2)) + "le"
        }
        // Default: male hard consonant → -e
        return name + "e"
    }

    static func stage(_ key: String?, detail: String? = nil) -> String {
        let lang = current
        let resolvedKey = key ?? "thinking"
        let label = stages[lang]?[resolvedKey] ?? stages["en"]?[resolvedKey] ?? stages["en"]?["thinking"] ?? "Thinking"
        if let detail = detail, !detail.isEmpty {
            // Prémiový formát: "Čtu soubor (ContentView.swift)" místo "Čtu soubor: ContentView.swift"
            return "\(label)  ·  \(detail)"
        }
        return label
    }
}
