import Foundation

struct L10n {
    static var current: String {
        UserDefaults.standard.string(forKey: "nova_lang") ?? "cs"
    }

    static let strings: [String: [String: String]] = [
        "cs": [
            "settings": "Nastavení", "save": "Uložit", "name": "Jméno", "cancel": "Zrušit",
            "personal_ai": "Tvoje osobní AI asistentka", "mac_server_info": "Tvůj Mac server běží Claude Code",
            "speak_now": "Mluvte...", "welcome_nova": "Vítej v Nově", "token_label": "Bezpečnostní token",
            "setup_desc": "Zadej adresu svého Mac serveru a bezpečnostní token pro připojení.",
            "name_placeholder": "Tvoje jméno", "city": "Domovské město",
            "city_placeholder": "Město", "language": "Jazyk",
            "voice": "Hlas asistenta", "female": "Ženský", "male": "Mužský",
            "connection": "Připojení", "connected": "Připojeno", "disconnected": "Odpojeno",
            "change_server": "Změnit server", "ready": "Připravena",
            "listening": "Poslouchám...", "thinking": "Přemýšlím...", "speaking": "Mluvím...",
            "write_nova": "Napiš Nově...", "you": "Ty", "send": "Odeslat",
            "connect": "Připojit", "server_title": "Připojení k serveru",
            "speech_recognition": "Rozpoznávání řeči", "stt_connected": "Připojeno",
            "stt_loading": "Načítám model...", "stt_error": "Chyba načtení", "stt_offline": "Nepřipojeno",
            "stt_desc": "WhisperKit on-device, auto-detect jazyka",
            "voice_id": "Voice ID", "voice_profile_active": "Hlasový profil aktivní",
            "voice_profile_none": "Hlasový profil nevytvořen",
            "voice_responds_you": "Nova reaguje jen na tebe", "face_id_voice": "Face ID pro tvůj hlas",
            "create_profile": "Vytvořit profil", "manage_profile": "Spravovat profil",
            "require_verification": "Vyžadovat ověření hlasu",
            "verify_on": "Nova reaguje jen pokud poznám tvůj hlas",
            "verify_off": "Nova reaguje na všechny mluvčí",
            "verification_strict": "Přísnost ověření", "last_match": "Poslední shoda",
            "permissive": "Permisivní", "balanced": "Vyvážené", "strict": "Přísné",
            "quick_actions": "Rychlé akce", "quick_actions_desc": "Tlačítka v hlavním chatu — tap = okamžitá akce",
            "action_name": "Název", "action_prompt": "Co říct Nově...", "add_action": "Přidat akci",
            "about": "O aplikaci", "version": "Verze", "developer": "Vývojář",
            "delete_history": "Smazat historii", "delete_history_confirm": "Smazat historii?",
            "delete_history_msg": "Tato akce je nevratná. Všechny zprávy v konverzaci budou smazány.",
            "delete": "Smazat", "what_today": "Co dnes potřebuješ?",
            "voice_unrecognized": "Hlas nepoznán",
            "dev_project": "Dev projekt",
            "memory": "Paměť Novy", "memory_facts": "Co si Nova pamatuje",
            "memory_empty": "Nova si zatím nic nepamatuje", "memory_delete_confirm": "Smazat tuto vzpomínku?",
            "memory_clear_all": "Smazat vše", "memory_clear_confirm": "Smazat všechny vzpomínky?",
            "memory_count": "vzpomínek",
        ],
        "en": [
            "settings": "Settings", "save": "Save", "name": "Name", "cancel": "Cancel",
            "personal_ai": "Your personal AI assistant", "mac_server_info": "Your Mac server runs Claude Code",
            "speak_now": "Speak...", "welcome_nova": "Welcome to Nova", "token_label": "Security token",
            "setup_desc": "Enter your Mac server address and security token to connect.",
            "name_placeholder": "Your name", "city": "Home city",
            "city_placeholder": "City", "language": "Language",
            "voice": "Assistant voice", "female": "Female", "male": "Male",
            "connection": "Connection", "connected": "Connected", "disconnected": "Disconnected",
            "change_server": "Change server", "ready": "Ready",
            "listening": "Listening...", "thinking": "Thinking...", "speaking": "Speaking...",
            "write_nova": "Write to Nova...", "you": "You", "send": "Send",
            "connect": "Connect", "server_title": "Connect to server",
            "speech_recognition": "Speech Recognition", "stt_connected": "Connected",
            "stt_loading": "Loading model...", "stt_error": "Load error", "stt_offline": "Offline",
            "stt_desc": "WhisperKit on-device, auto language detection",
            "voice_id": "Voice ID", "voice_profile_active": "Voice profile active",
            "voice_profile_none": "Voice profile not created",
            "voice_responds_you": "Nova responds only to you", "face_id_voice": "Face ID for your voice",
            "create_profile": "Create profile", "manage_profile": "Manage profile",
            "require_verification": "Require voice verification",
            "verify_on": "Nova responds only when your voice is recognized",
            "verify_off": "Nova responds to all speakers",
            "verification_strict": "Verification strictness", "last_match": "Last match",
            "permissive": "Permissive", "balanced": "Balanced", "strict": "Strict",
            "quick_actions": "Quick Actions", "quick_actions_desc": "Buttons in main chat — tap for instant action",
            "action_name": "Name", "action_prompt": "What to tell Nova...", "add_action": "Add action",
            "about": "About", "version": "Version", "developer": "Developer",
            "delete_history": "Delete history", "delete_history_confirm": "Delete history?",
            "delete_history_msg": "This action cannot be undone. All messages will be deleted.",
            "delete": "Delete", "what_today": "What do you need today?",
            "voice_unrecognized": "Voice not recognized",
            "dev_project": "Dev project",
            "memory": "Nova's Memory", "memory_facts": "What Nova remembers",
            "memory_empty": "Nova doesn't remember anything yet", "memory_delete_confirm": "Delete this memory?",
            "memory_clear_all": "Clear all", "memory_clear_confirm": "Delete all memories?",
            "memory_count": "memories",
        ],
        "de": [
            "settings": "Einstellungen", "save": "Speichern", "name": "Name", "cancel": "Abbrechen",
            "personal_ai": "Dein persönlicher KI-Assistent", "mac_server_info": "Dein Mac-Server läuft mit Claude Code",
            "speak_now": "Sprechen...", "welcome_nova": "Willkommen bei Nova", "token_label": "Sicherheitstoken",
            "setup_desc": "Gib die Adresse deines Mac-Servers und den Sicherheitstoken ein.",
            "name_placeholder": "Dein Name", "city": "Heimatstadt",
            "city_placeholder": "Stadt", "language": "Sprache",
            "voice": "Assistentenstimme", "female": "Weiblich", "male": "Männlich",
            "connection": "Verbindung", "connected": "Verbunden", "disconnected": "Getrennt",
            "change_server": "Server ändern", "ready": "Bereit",
            "listening": "Höre zu...", "thinking": "Denke nach...", "speaking": "Spreche...",
            "write_nova": "Schreib Nova...", "you": "Du", "send": "Senden",
            "connect": "Verbinden", "server_title": "Mit Server verbinden",
            "speech_recognition": "Spracherkennung", "stt_connected": "Verbunden",
            "stt_loading": "Modell laden...", "stt_error": "Ladefehler", "stt_offline": "Offline",
            "stt_desc": "WhisperKit on-device, automatische Spracherkennung",
            "voice_id": "Voice ID", "voice_profile_active": "Stimmprofil aktiv",
            "voice_profile_none": "Kein Stimmprofil erstellt",
            "voice_responds_you": "Nova reagiert nur auf dich", "face_id_voice": "Face ID für deine Stimme",
            "create_profile": "Profil erstellen", "manage_profile": "Profil verwalten",
            "require_verification": "Stimmverifizierung erforderlich",
            "verify_on": "Nova reagiert nur bei erkannter Stimme",
            "verify_off": "Nova reagiert auf alle Sprecher",
            "verification_strict": "Verifizierungsstrenge", "last_match": "Letzte Übereinstimmung",
            "permissive": "Tolerant", "balanced": "Ausgewogen", "strict": "Streng",
            "quick_actions": "Schnellaktionen", "quick_actions_desc": "Buttons im Chat — tippen für sofortige Aktion",
            "action_name": "Name", "action_prompt": "Was Nova sagen...", "add_action": "Aktion hinzufügen",
            "about": "Über die App", "version": "Version", "developer": "Entwickler",
            "delete_history": "Verlauf löschen", "delete_history_confirm": "Verlauf löschen?",
            "delete_history_msg": "Diese Aktion kann nicht rückgängig gemacht werden.",
            "delete": "Löschen", "what_today": "Was brauchst du heute?",
            "voice_unrecognized": "Stimme nicht erkannt",
            "dev_project": "Dev-Projekt",
            "memory": "Novas Gedächtnis", "memory_facts": "Was Nova sich merkt",
            "memory_empty": "Nova erinnert sich noch an nichts", "memory_delete_confirm": "Diese Erinnerung löschen?",
            "memory_clear_all": "Alles löschen", "memory_clear_confirm": "Alle Erinnerungen löschen?",
            "memory_count": "Erinnerungen",
        ],
        "fr": [
            "settings": "Paramètres", "save": "Enregistrer", "name": "Nom", "cancel": "Annuler",
            "personal_ai": "Ton assistant IA personnel", "mac_server_info": "Ton serveur Mac utilise Claude Code",
            "speak_now": "Parle...", "welcome_nova": "Bienvenue sur Nova", "token_label": "Jeton de sécurité",
            "setup_desc": "Entre l'adresse de ton serveur Mac et le jeton de sécurité.",
            "name_placeholder": "Ton nom", "city": "Ville",
            "city_placeholder": "Ville", "language": "Langue",
            "voice": "Voix de l'assistant", "female": "Féminine", "male": "Masculine",
            "connection": "Connexion", "connected": "Connecté", "disconnected": "Déconnecté",
            "change_server": "Changer de serveur", "ready": "Prête",
            "listening": "J'écoute...", "thinking": "Je réfléchis...", "speaking": "Je parle...",
            "write_nova": "Écris à Nova...", "you": "Toi", "send": "Envoyer",
            "connect": "Connecter", "server_title": "Connexion au serveur",
            "speech_recognition": "Reconnaissance vocale", "stt_connected": "Connecté",
            "stt_loading": "Chargement du modèle...", "stt_error": "Erreur de chargement", "stt_offline": "Hors ligne",
            "stt_desc": "WhisperKit on-device, détection automatique de la langue",
            "voice_id": "Voice ID", "voice_profile_active": "Profil vocal actif",
            "voice_profile_none": "Profil vocal non créé",
            "voice_responds_you": "Nova ne répond qu'à toi", "face_id_voice": "Face ID pour ta voix",
            "create_profile": "Créer un profil", "manage_profile": "Gérer le profil",
            "require_verification": "Exiger la vérification vocale",
            "verify_on": "Nova ne répond que si ta voix est reconnue",
            "verify_off": "Nova répond à tous les interlocuteurs",
            "verification_strict": "Rigueur de vérification", "last_match": "Dernière correspondance",
            "permissive": "Permissif", "balanced": "Équilibré", "strict": "Strict",
            "quick_actions": "Actions rapides", "quick_actions_desc": "Boutons dans le chat — appui pour action instantanée",
            "action_name": "Nom", "action_prompt": "Que dire à Nova...", "add_action": "Ajouter une action",
            "about": "À propos", "version": "Version", "developer": "Développeur",
            "delete_history": "Supprimer l'historique", "delete_history_confirm": "Supprimer l'historique?",
            "delete_history_msg": "Cette action est irréversible. Tous les messages seront supprimés.",
            "delete": "Supprimer", "what_today": "De quoi as-tu besoin aujourd'hui?",
            "voice_unrecognized": "Voix non reconnue",
            "dev_project": "Projet dev",
            "memory": "Mémoire de Nova", "memory_facts": "Ce que Nova retient",
            "memory_empty": "Nova ne se souvient de rien encore", "memory_delete_confirm": "Supprimer ce souvenir ?",
            "memory_clear_all": "Tout supprimer", "memory_clear_confirm": "Supprimer tous les souvenirs ?",
            "memory_count": "souvenirs",
        ],
        "es": [
            "settings": "Ajustes", "save": "Guardar", "name": "Nombre", "cancel": "Cancelar",
            "personal_ai": "Tu asistente IA personal", "mac_server_info": "Tu servidor Mac ejecuta Claude Code",
            "speak_now": "Habla...", "welcome_nova": "Bienvenido a Nova", "token_label": "Token de seguridad",
            "setup_desc": "Ingresa la dirección de tu servidor Mac y el token de seguridad.",
            "name_placeholder": "Tu nombre", "city": "Ciudad",
            "city_placeholder": "Ciudad", "language": "Idioma",
            "voice": "Voz del asistente", "female": "Femenina", "male": "Masculina",
            "connection": "Conexión", "connected": "Conectado", "disconnected": "Desconectado",
            "change_server": "Cambiar servidor", "ready": "Lista",
            "listening": "Escuchando...", "thinking": "Pensando...", "speaking": "Hablando...",
            "write_nova": "Escribe a Nova...", "you": "Tú", "send": "Enviar",
            "connect": "Conectar", "server_title": "Conexión al servidor",
            "speech_recognition": "Reconocimiento de voz", "stt_connected": "Conectado",
            "stt_loading": "Cargando modelo...", "stt_error": "Error de carga", "stt_offline": "Sin conexión",
            "stt_desc": "WhisperKit on-device, detección automática de idioma",
            "voice_id": "Voice ID", "voice_profile_active": "Perfil de voz activo",
            "voice_profile_none": "Perfil de voz no creado",
            "voice_responds_you": "Nova responde solo a ti", "face_id_voice": "Face ID para tu voz",
            "create_profile": "Crear perfil", "manage_profile": "Gestionar perfil",
            "require_verification": "Requerir verificación de voz",
            "verify_on": "Nova responde solo cuando reconoce tu voz",
            "verify_off": "Nova responde a todos",
            "verification_strict": "Rigurosidad", "last_match": "Última coincidencia",
            "permissive": "Permisivo", "balanced": "Equilibrado", "strict": "Estricto",
            "quick_actions": "Acciones rápidas", "quick_actions_desc": "Botones en el chat — toca para acción instantánea",
            "action_name": "Nombre", "action_prompt": "Qué decirle a Nova...", "add_action": "Añadir acción",
            "about": "Acerca de", "version": "Versión", "developer": "Desarrollador",
            "delete_history": "Borrar historial", "delete_history_confirm": "¿Borrar historial?",
            "delete_history_msg": "Esta acción no se puede deshacer. Todos los mensajes se eliminarán.",
            "delete": "Borrar", "what_today": "¿Qué necesitas hoy?",
            "voice_unrecognized": "Voz no reconocida",
            "dev_project": "Proyecto dev",
            "memory": "Memoria de Nova", "memory_facts": "Lo que Nova recuerda",
            "memory_empty": "Nova aún no recuerda nada", "memory_delete_confirm": "¿Eliminar este recuerdo?",
            "memory_clear_all": "Borrar todo", "memory_clear_confirm": "¿Eliminar todos los recuerdos?",
            "memory_count": "recuerdos",
        ],
        "ja": [
            "settings": "設定", "save": "保存", "name": "名前", "cancel": "キャンセル",
            "name_placeholder": "あなたの名前", "city": "ホームシティ",
            "city_placeholder": "都市", "language": "言語",
            "voice": "アシスタントの声", "female": "女性", "male": "男性",
            "connection": "接続", "connected": "接続済み", "disconnected": "未接続",
            "change_server": "サーバー変更", "ready": "準備完了",
            "listening": "聞いています...", "thinking": "考えています...", "speaking": "話しています...",
            "write_nova": "Novaに書く...", "you": "あなた", "send": "送信",
            "connect": "接続", "server_title": "サーバーに接続",
            "speech_recognition": "音声認識", "stt_connected": "接続済み",
            "stt_loading": "モデル読込中...", "stt_error": "読込エラー", "stt_offline": "オフライン",
            "stt_desc": "WhisperKit オンデバイス、言語自動検出",
            "voice_id": "Voice ID", "voice_profile_active": "音声プロファイル有効",
            "voice_profile_none": "音声プロファイル未作成",
            "voice_responds_you": "Novaはあなただけに応答します", "face_id_voice": "声のFace ID",
            "create_profile": "プロファイル作成", "manage_profile": "プロファイル管理",
            "require_verification": "音声認証を要求",
            "verify_on": "声が認識された時のみ応答",
            "verify_off": "全ての話者に応答",
            "verification_strict": "認証厳格度", "last_match": "最後の一致",
            "permissive": "寛容", "balanced": "バランス", "strict": "厳格",
            "quick_actions": "クイックアクション", "quick_actions_desc": "チャットのボタン — タップで即時実行",
            "action_name": "名前", "action_prompt": "Novaに伝えること...", "add_action": "アクション追加",
            "about": "アプリについて", "version": "バージョン", "developer": "開発者",
            "delete_history": "履歴削除", "delete_history_confirm": "履歴を削除しますか？",
            "delete_history_msg": "この操作は元に戻せません。すべてのメッセージが削除されます。",
            "delete": "削除", "what_today": "今日は何が必要ですか？",
            "voice_unrecognized": "声が認識されません",
            "dev_project": "開発プロジェクト",
            "memory": "Novaの記憶", "memory_facts": "Novaが覚えていること",
            "memory_empty": "Novaはまだ何も覚えていません", "memory_delete_confirm": "この記憶を削除しますか？",
            "memory_clear_all": "すべて削除", "memory_clear_confirm": "すべての記憶を削除しますか？",
            "memory_count": "件の記憶",
        ],
        "zh": [
            "settings": "设置", "save": "保存", "name": "姓名", "cancel": "取消",
            "name_placeholder": "你的名字", "city": "所在城市",
            "city_placeholder": "城市", "language": "语言",
            "voice": "助手语音", "female": "女声", "male": "男声",
            "connection": "连接", "connected": "已连接", "disconnected": "未连接",
            "change_server": "更改服务器", "ready": "就绪",
            "listening": "聆听中...", "thinking": "思考中...", "speaking": "说话中...",
            "write_nova": "写给Nova...", "you": "你", "send": "发送",
            "connect": "连接", "server_title": "连接到服务器",
            "speech_recognition": "语音识别", "stt_connected": "已连接",
            "stt_loading": "加载模型中...", "stt_error": "加载错误", "stt_offline": "离线",
            "stt_desc": "WhisperKit 本地运行，自动语言检测",
            "voice_id": "Voice ID", "voice_profile_active": "声纹已激活",
            "voice_profile_none": "声纹未创建",
            "voice_responds_you": "Nova只回应你", "face_id_voice": "语音Face ID",
            "create_profile": "创建声纹", "manage_profile": "管理声纹",
            "require_verification": "要求语音验证",
            "verify_on": "仅在识别你的声音时回应",
            "verify_off": "回应所有说话者",
            "verification_strict": "验证严格度", "last_match": "最后匹配",
            "permissive": "宽松", "balanced": "平衡", "strict": "严格",
            "quick_actions": "快捷操作", "quick_actions_desc": "聊天中的按钮 — 点击即时执行",
            "action_name": "名称", "action_prompt": "对Nova说...", "add_action": "添加操作",
            "about": "关于", "version": "版本", "developer": "开发者",
            "delete_history": "删除历史", "delete_history_confirm": "删除历史？",
            "delete_history_msg": "此操作不可撤销。所有消息将被删除。",
            "delete": "删除", "what_today": "今天需要什么？",
            "voice_unrecognized": "声音未识别",
            "dev_project": "开发项目",
            "memory": "Nova的记忆", "memory_facts": "Nova记住的内容",
            "memory_empty": "Nova还没有任何记忆", "memory_delete_confirm": "删除这条记忆？",
            "memory_clear_all": "全部删除", "memory_clear_confirm": "删除所有记忆？",
            "memory_count": "条记忆",
        ],
        "ar": [
            "settings": "الإعدادات", "save": "حفظ", "name": "الاسم", "cancel": "إلغاء",
            "personal_ai": "مساعدتك الشخصية بالذكاء الاصطناعي", "mac_server_info": "خادم Mac يعمل بـ Claude Code",
            "speak_now": "تحدّث...", "welcome_nova": "مرحباً بك في Nova", "token_label": "رمز الأمان",
            "setup_desc": "أدخل عنوان خادم Mac ورمز الأمان للاتصال.",
            "name_placeholder": "اسمك", "city": "المدينة",
            "city_placeholder": "المدينة", "language": "اللغة",
            "voice": "صوت المساعد", "female": "أنثوي", "male": "ذكوري",
            "connection": "الاتصال", "connected": "متصل", "disconnected": "غير متصل",
            "change_server": "تغيير الخادم", "ready": "جاهزة",
            "listening": "أستمع...", "thinking": "أفكّر...", "speaking": "أتحدّث...",
            "write_nova": "اكتب لـ Nova...", "you": "أنت", "send": "إرسال",
            "connect": "اتصال", "server_title": "الاتصال بالخادم",
            "speech_recognition": "التعرّف على الصوت", "stt_connected": "متصل",
            "stt_loading": "جارٍ تحميل النموذج...", "stt_error": "خطأ في التحميل", "stt_offline": "غير متصل",
            "stt_desc": "WhisperKit على الجهاز، كشف تلقائي للغة",
            "voice_id": "Voice ID", "voice_profile_active": "البصمة الصوتية مفعّلة",
            "voice_profile_none": "لم يتم إنشاء بصمة صوتية",
            "voice_responds_you": "Nova تستجيب لك فقط", "face_id_voice": "Face ID لصوتك",
            "create_profile": "إنشاء بصمة", "manage_profile": "إدارة البصمة",
            "require_verification": "طلب التحقق الصوتي",
            "verify_on": "Nova تستجيب فقط عند التعرّف على صوتك",
            "verify_off": "Nova تستجيب لجميع المتحدثين",
            "verification_strict": "صرامة التحقق", "last_match": "آخر تطابق",
            "permissive": "متساهل", "balanced": "متوازن", "strict": "صارم",
            "quick_actions": "إجراءات سريعة", "quick_actions_desc": "أزرار في المحادثة — انقر لتنفيذ فوري",
            "action_name": "الاسم", "action_prompt": "ماذا تقول لـ Nova...", "add_action": "إضافة إجراء",
            "about": "حول التطبيق", "version": "الإصدار", "developer": "المطوّر",
            "delete_history": "حذف السجل", "delete_history_confirm": "حذف السجل؟",
            "delete_history_msg": "لا يمكن التراجع عن هذا الإجراء. سيتم حذف جميع الرسائل.",
            "delete": "حذف", "what_today": "ماذا تحتاج اليوم؟",
            "voice_unrecognized": "لم يتم التعرّف على الصوت",
            "dev_project": "مشروع تطوير",
            "memory": "ذاكرة Nova", "memory_facts": "ما تتذكره Nova",
            "memory_empty": "لا تتذكر Nova أي شيء بعد", "memory_delete_confirm": "حذف هذه الذكرى؟",
            "memory_clear_all": "حذف الكل", "memory_clear_confirm": "حذف جميع الذكريات؟",
            "memory_count": "ذكريات",
        ],
        "hi": [
            "settings": "सेटिंग्स", "save": "सहेजें", "name": "नाम", "cancel": "रद्द करें",
            "personal_ai": "आपकी निजी AI सहायक", "mac_server_info": "आपका Mac सर्वर Claude Code चला रहा है",
            "speak_now": "बोलें...", "welcome_nova": "Nova में आपका स्वागत है", "token_label": "सुरक्षा टोकन",
            "setup_desc": "कनेक्ट करने के लिए अपने Mac सर्वर का पता और सुरक्षा टोकन दर्ज करें।",
            "name_placeholder": "आपका नाम", "city": "शहर",
            "city_placeholder": "शहर", "language": "भाषा",
            "voice": "सहायक की आवाज़", "female": "महिला", "male": "पुरुष",
            "connection": "कनेक्शन", "connected": "कनेक्टेड", "disconnected": "डिस्कनेक्टेड",
            "change_server": "सर्वर बदलें", "ready": "तैयार",
            "listening": "सुन रही हूँ...", "thinking": "सोच रही हूँ...", "speaking": "बोल रही हूँ...",
            "write_nova": "Nova को लिखें...", "you": "आप", "send": "भेजें",
            "connect": "कनेक्ट करें", "server_title": "सर्वर से कनेक्ट करें",
            "speech_recognition": "वाक् पहचान", "stt_connected": "कनेक्टेड",
            "stt_loading": "मॉडल लोड हो रहा है...", "stt_error": "लोड त्रुटि", "stt_offline": "ऑफ़लाइन",
            "stt_desc": "WhisperKit ऑन-डिवाइस, स्वचालित भाषा पहचान",
            "voice_id": "Voice ID", "voice_profile_active": "वॉइस प्रोफ़ाइल सक्रिय",
            "voice_profile_none": "वॉइस प्रोफ़ाइल नहीं बनाई गई",
            "voice_responds_you": "Nova केवल आपको जवाब देती है", "face_id_voice": "आपकी आवाज़ के लिए Face ID",
            "create_profile": "प्रोफ़ाइल बनाएँ", "manage_profile": "प्रोफ़ाइल प्रबंधित करें",
            "require_verification": "वॉइस सत्यापन आवश्यक",
            "verify_on": "Nova केवल तब जवाब देती है जब आपकी आवाज़ पहचानी जाए",
            "verify_off": "Nova सभी वक्ताओं को जवाब देती है",
            "verification_strict": "सत्यापन कड़ाई", "last_match": "अंतिम मिलान",
            "permissive": "उदार", "balanced": "संतुलित", "strict": "सख़्त",
            "quick_actions": "त्वरित कार्य", "quick_actions_desc": "चैट में बटन — टैप करें तुरंत कार्य के लिए",
            "action_name": "नाम", "action_prompt": "Nova से क्या कहें...", "add_action": "कार्य जोड़ें",
            "about": "ऐप के बारे में", "version": "संस्करण", "developer": "डेवलपर",
            "delete_history": "इतिहास मिटाएँ", "delete_history_confirm": "इतिहास मिटाएँ?",
            "delete_history_msg": "यह क्रिया पूर्ववत नहीं की जा सकती। सभी संदेश हटा दिए जाएँगे।",
            "delete": "मिटाएँ", "what_today": "आज आपको क्या चाहिए?",
            "voice_unrecognized": "आवाज़ पहचानी नहीं गई",
            "dev_project": "डेव प्रोजेक्ट",
            "memory": "Nova की स्मृति", "memory_facts": "Nova को क्या याद है",
            "memory_empty": "Nova को अभी कुछ भी याद नहीं है", "memory_delete_confirm": "यह स्मृति मिटाएँ?",
            "memory_clear_all": "सब मिटाएँ", "memory_clear_confirm": "सभी स्मृतियाँ मिटाएँ?",
            "memory_count": "स्मृतियाँ",
        ],
        "it": [
            "settings": "Impostazioni", "save": "Salva", "name": "Nome", "cancel": "Annulla",
            "personal_ai": "La tua assistente IA personale", "mac_server_info": "Il tuo server Mac esegue Claude Code",
            "speak_now": "Parla...", "welcome_nova": "Benvenuto in Nova", "token_label": "Token di sicurezza",
            "setup_desc": "Inserisci l'indirizzo del tuo server Mac e il token di sicurezza per connetterti.",
            "name_placeholder": "Il tuo nome", "city": "Città",
            "city_placeholder": "Città", "language": "Lingua",
            "voice": "Voce dell'assistente", "female": "Femminile", "male": "Maschile",
            "connection": "Connessione", "connected": "Connesso", "disconnected": "Disconnesso",
            "change_server": "Cambia server", "ready": "Pronta",
            "listening": "Ascolto...", "thinking": "Penso...", "speaking": "Parlo...",
            "write_nova": "Scrivi a Nova...", "you": "Tu", "send": "Invia",
            "connect": "Connetti", "server_title": "Connessione al server",
            "speech_recognition": "Riconoscimento vocale", "stt_connected": "Connesso",
            "stt_loading": "Caricamento modello...", "stt_error": "Errore di caricamento", "stt_offline": "Offline",
            "stt_desc": "WhisperKit on-device, rilevamento automatico della lingua",
            "voice_id": "Voice ID", "voice_profile_active": "Profilo vocale attivo",
            "voice_profile_none": "Profilo vocale non creato",
            "voice_responds_you": "Nova risponde solo a te", "face_id_voice": "Face ID per la tua voce",
            "create_profile": "Crea profilo", "manage_profile": "Gestisci profilo",
            "require_verification": "Richiedi verifica vocale",
            "verify_on": "Nova risponde solo quando riconosce la tua voce",
            "verify_off": "Nova risponde a tutti",
            "verification_strict": "Rigore della verifica", "last_match": "Ultima corrispondenza",
            "permissive": "Permissivo", "balanced": "Bilanciato", "strict": "Rigoroso",
            "quick_actions": "Azioni rapide", "quick_actions_desc": "Pulsanti nella chat — tocca per azione istantanea",
            "action_name": "Nome", "action_prompt": "Cosa dire a Nova...", "add_action": "Aggiungi azione",
            "about": "Info", "version": "Versione", "developer": "Sviluppatore",
            "delete_history": "Elimina cronologia", "delete_history_confirm": "Eliminare la cronologia?",
            "delete_history_msg": "Questa azione non può essere annullata. Tutti i messaggi verranno eliminati.",
            "delete": "Elimina", "what_today": "Di cosa hai bisogno oggi?",
            "voice_unrecognized": "Voce non riconosciuta",
            "dev_project": "Progetto dev",
            "memory": "Memoria di Nova", "memory_facts": "Cosa ricorda Nova",
            "memory_empty": "Nova non ricorda ancora nulla", "memory_delete_confirm": "Eliminare questo ricordo?",
            "memory_clear_all": "Elimina tutto", "memory_clear_confirm": "Eliminare tutti i ricordi?",
            "memory_count": "ricordi",
        ],
        "ko": [
            "settings": "설정", "save": "저장", "name": "이름", "cancel": "취소",
            "personal_ai": "당신의 개인 AI 어시스턴트", "mac_server_info": "Mac 서버에서 Claude Code 실행 중",
            "speak_now": "말하세요...", "welcome_nova": "Nova에 오신 것을 환영합니다", "token_label": "보안 토큰",
            "setup_desc": "Mac 서버 주소와 보안 토큰을 입력하여 연결하세요.",
            "name_placeholder": "이름", "city": "도시",
            "city_placeholder": "도시", "language": "언어",
            "voice": "어시스턴트 음성", "female": "여성", "male": "남성",
            "connection": "연결", "connected": "연결됨", "disconnected": "연결 끊김",
            "change_server": "서버 변경", "ready": "준비 완료",
            "listening": "듣는 중...", "thinking": "생각 중...", "speaking": "말하는 중...",
            "write_nova": "Nova에게 쓰기...", "you": "나", "send": "보내기",
            "connect": "연결", "server_title": "서버에 연결",
            "speech_recognition": "음성 인식", "stt_connected": "연결됨",
            "stt_loading": "모델 로딩 중...", "stt_error": "로딩 오류", "stt_offline": "오프라인",
            "stt_desc": "WhisperKit 온디바이스, 자동 언어 감지",
            "voice_id": "Voice ID", "voice_profile_active": "음성 프로필 활성",
            "voice_profile_none": "음성 프로필 미생성",
            "voice_responds_you": "Nova가 당신에게만 응답합니다", "face_id_voice": "음성용 Face ID",
            "create_profile": "프로필 생성", "manage_profile": "프로필 관리",
            "require_verification": "음성 인증 필요",
            "verify_on": "음성이 인식될 때만 Nova가 응답합니다",
            "verify_off": "Nova가 모든 화자에게 응답합니다",
            "verification_strict": "인증 엄격도", "last_match": "마지막 일치",
            "permissive": "관대", "balanced": "균형", "strict": "엄격",
            "quick_actions": "빠른 동작", "quick_actions_desc": "채팅의 버튼 — 탭하여 즉시 실행",
            "action_name": "이름", "action_prompt": "Nova에게 할 말...", "add_action": "동작 추가",
            "about": "앱 정보", "version": "버전", "developer": "개발자",
            "delete_history": "기록 삭제", "delete_history_confirm": "기록을 삭제할까요?",
            "delete_history_msg": "이 작업은 되돌릴 수 없습니다. 모든 메시지가 삭제됩니다.",
            "delete": "삭제", "what_today": "오늘 무엇이 필요하세요?",
            "voice_unrecognized": "음성을 인식할 수 없음",
            "dev_project": "개발 프로젝트",
            "memory": "Nova의 기억", "memory_facts": "Nova가 기억하는 것",
            "memory_empty": "Nova는 아직 아무것도 기억하지 못합니다", "memory_delete_confirm": "이 기억을 삭제할까요?",
            "memory_clear_all": "모두 삭제", "memory_clear_confirm": "모든 기억을 삭제할까요?",
            "memory_count": "개의 기억",
        ],
        "pl": [
            "settings": "Ustawienia", "save": "Zapisz", "name": "Imię", "cancel": "Anuluj",
            "personal_ai": "Twoja osobista asystentka AI", "mac_server_info": "Twój serwer Mac używa Claude Code",
            "speak_now": "Mów...", "welcome_nova": "Witaj w Nova", "token_label": "Token bezpieczeństwa",
            "setup_desc": "Wpisz adres serwera Mac i token bezpieczeństwa, aby się połączyć.",
            "name_placeholder": "Twoje imię", "city": "Miasto",
            "city_placeholder": "Miasto", "language": "Język",
            "voice": "Głos asystenta", "female": "Kobiecy", "male": "Męski",
            "connection": "Połączenie", "connected": "Połączono", "disconnected": "Rozłączono",
            "change_server": "Zmień serwer", "ready": "Gotowa",
            "listening": "Słucham...", "thinking": "Myślę...", "speaking": "Mówię...",
            "write_nova": "Napisz do Novy...", "you": "Ty", "send": "Wyślij",
            "connect": "Połącz", "server_title": "Połączenie z serwerem",
            "speech_recognition": "Rozpoznawanie mowy", "stt_connected": "Połączono",
            "stt_loading": "Ładowanie modelu...", "stt_error": "Błąd ładowania", "stt_offline": "Offline",
            "stt_desc": "WhisperKit on-device, automatyczne wykrywanie języka",
            "voice_id": "Voice ID", "voice_profile_active": "Profil głosowy aktywny",
            "voice_profile_none": "Profil głosowy nie utworzony",
            "voice_responds_you": "Nova odpowiada tylko tobie", "face_id_voice": "Face ID dla twojego głosu",
            "create_profile": "Utwórz profil", "manage_profile": "Zarządzaj profilem",
            "require_verification": "Wymagaj weryfikacji głosu",
            "verify_on": "Nova odpowiada tylko po rozpoznaniu twojego głosu",
            "verify_off": "Nova odpowiada wszystkim mówcom",
            "verification_strict": "Rygorystyczność weryfikacji", "last_match": "Ostatnie dopasowanie",
            "permissive": "Łagodny", "balanced": "Zrównoważony", "strict": "Rygorystyczny",
            "quick_actions": "Szybkie akcje", "quick_actions_desc": "Przyciski na czacie — dotknij, by wykonać natychmiast",
            "action_name": "Nazwa", "action_prompt": "Co powiedzieć Novie...", "add_action": "Dodaj akcję",
            "about": "O aplikacji", "version": "Wersja", "developer": "Deweloper",
            "delete_history": "Usuń historię", "delete_history_confirm": "Usunąć historię?",
            "delete_history_msg": "Tej czynności nie można cofnąć. Wszystkie wiadomości zostaną usunięte.",
            "delete": "Usuń", "what_today": "Czego dziś potrzebujesz?",
            "voice_unrecognized": "Głos nierozpoznany",
            "dev_project": "Projekt dev",
            "memory": "Pamięć Novy", "memory_facts": "Co Nova pamięta",
            "memory_empty": "Nova jeszcze niczego nie pamięta", "memory_delete_confirm": "Usunąć to wspomnienie?",
            "memory_clear_all": "Usuń wszystko", "memory_clear_confirm": "Usunąć wszystkie wspomnienia?",
            "memory_count": "wspomnień",
        ],
        "pt": [
            "settings": "Configurações", "save": "Salvar", "name": "Nome", "cancel": "Cancelar",
            "personal_ai": "Sua assistente pessoal de IA", "mac_server_info": "Seu servidor Mac roda Claude Code",
            "speak_now": "Fale...", "welcome_nova": "Bem-vindo ao Nova", "token_label": "Token de segurança",
            "setup_desc": "Digite o endereço do seu servidor Mac e o token de segurança para conectar.",
            "name_placeholder": "Seu nome", "city": "Cidade",
            "city_placeholder": "Cidade", "language": "Idioma",
            "voice": "Voz do assistente", "female": "Feminina", "male": "Masculina",
            "connection": "Conexão", "connected": "Conectado", "disconnected": "Desconectado",
            "change_server": "Alterar servidor", "ready": "Pronta",
            "listening": "Ouvindo...", "thinking": "Pensando...", "speaking": "Falando...",
            "write_nova": "Escreva para Nova...", "you": "Você", "send": "Enviar",
            "connect": "Conectar", "server_title": "Conexão com o servidor",
            "speech_recognition": "Reconhecimento de voz", "stt_connected": "Conectado",
            "stt_loading": "Carregando modelo...", "stt_error": "Erro ao carregar", "stt_offline": "Offline",
            "stt_desc": "WhisperKit no dispositivo, detecção automática de idioma",
            "voice_id": "Voice ID", "voice_profile_active": "Perfil de voz ativo",
            "voice_profile_none": "Perfil de voz não criado",
            "voice_responds_you": "Nova responde apenas a você", "face_id_voice": "Face ID para sua voz",
            "create_profile": "Criar perfil", "manage_profile": "Gerenciar perfil",
            "require_verification": "Exigir verificação de voz",
            "verify_on": "Nova responde apenas quando sua voz é reconhecida",
            "verify_off": "Nova responde a todos",
            "verification_strict": "Rigor da verificação", "last_match": "Última correspondência",
            "permissive": "Permissivo", "balanced": "Equilibrado", "strict": "Rigoroso",
            "quick_actions": "Ações rápidas", "quick_actions_desc": "Botões no chat — toque para ação instantânea",
            "action_name": "Nome", "action_prompt": "O que dizer à Nova...", "add_action": "Adicionar ação",
            "about": "Sobre", "version": "Versão", "developer": "Desenvolvedor",
            "delete_history": "Apagar histórico", "delete_history_confirm": "Apagar histórico?",
            "delete_history_msg": "Esta ação não pode ser desfeita. Todas as mensagens serão apagadas.",
            "delete": "Apagar", "what_today": "Do que você precisa hoje?",
            "voice_unrecognized": "Voz não reconhecida",
            "dev_project": "Projeto dev",
            "memory": "Memória da Nova", "memory_facts": "O que a Nova lembra",
            "memory_empty": "A Nova ainda não se lembra de nada", "memory_delete_confirm": "Apagar esta memória?",
            "memory_clear_all": "Apagar tudo", "memory_clear_confirm": "Apagar todas as memórias?",
            "memory_count": "memórias",
        ],
        "ru": [
            "settings": "Настройки", "save": "Сохранить", "name": "Имя", "cancel": "Отмена",
            "personal_ai": "Ваш персональный ИИ-ассистент", "mac_server_info": "Ваш Mac-сервер работает на Claude Code",
            "speak_now": "Говорите...", "welcome_nova": "Добро пожаловать в Nova", "token_label": "Токен безопасности",
            "setup_desc": "Введите адрес вашего Mac-сервера и токен безопасности для подключения.",
            "name_placeholder": "Ваше имя", "city": "Город",
            "city_placeholder": "Город", "language": "Язык",
            "voice": "Голос ассистента", "female": "Женский", "male": "Мужской",
            "connection": "Подключение", "connected": "Подключено", "disconnected": "Отключено",
            "change_server": "Сменить сервер", "ready": "Готова",
            "listening": "Слушаю...", "thinking": "Думаю...", "speaking": "Говорю...",
            "write_nova": "Напишите Nova...", "you": "Вы", "send": "Отправить",
            "connect": "Подключить", "server_title": "Подключение к серверу",
            "speech_recognition": "Распознавание речи", "stt_connected": "Подключено",
            "stt_loading": "Загрузка модели...", "stt_error": "Ошибка загрузки", "stt_offline": "Не в сети",
            "stt_desc": "WhisperKit на устройстве, автоопределение языка",
            "voice_id": "Voice ID", "voice_profile_active": "Голосовой профиль активен",
            "voice_profile_none": "Голосовой профиль не создан",
            "voice_responds_you": "Nova отвечает только вам", "face_id_voice": "Face ID для вашего голоса",
            "create_profile": "Создать профиль", "manage_profile": "Управление профилем",
            "require_verification": "Требовать голосовую верификацию",
            "verify_on": "Nova отвечает только при распознании вашего голоса",
            "verify_off": "Nova отвечает всем говорящим",
            "verification_strict": "Строгость верификации", "last_match": "Последнее совпадение",
            "permissive": "Мягкий", "balanced": "Сбалансированный", "strict": "Строгий",
            "quick_actions": "Быстрые действия", "quick_actions_desc": "Кнопки в чате — нажмите для мгновенного действия",
            "action_name": "Название", "action_prompt": "Что сказать Nova...", "add_action": "Добавить действие",
            "about": "О приложении", "version": "Версия", "developer": "Разработчик",
            "delete_history": "Удалить историю", "delete_history_confirm": "Удалить историю?",
            "delete_history_msg": "Это действие нельзя отменить. Все сообщения будут удалены.",
            "delete": "Удалить", "what_today": "Что вам нужно сегодня?",
            "voice_unrecognized": "Голос не распознан",
            "dev_project": "Dev-проект",
            "memory": "Память Nova", "memory_facts": "Что помнит Nova",
            "memory_empty": "Nova пока ничего не помнит", "memory_delete_confirm": "Удалить это воспоминание?",
            "memory_clear_all": "Удалить всё", "memory_clear_confirm": "Удалить все воспоминания?",
            "memory_count": "воспоминаний",
        ],
        "sk": [
            "settings": "Nastavenia", "save": "Uložiť", "name": "Meno", "cancel": "Zrušiť",
            "personal_ai": "Tvoja osobná AI asistentka", "mac_server_info": "Tvoj Mac server beží na Claude Code",
            "speak_now": "Hovorte...", "welcome_nova": "Vitaj v Nova", "token_label": "Bezpečnostný token",
            "setup_desc": "Zadaj adresu svojho Mac servera a bezpečnostný token na pripojenie.",
            "name_placeholder": "Tvoje meno", "city": "Domovské mesto",
            "city_placeholder": "Mesto", "language": "Jazyk",
            "voice": "Hlas asistenta", "female": "Ženský", "male": "Mužský",
            "connection": "Pripojenie", "connected": "Pripojené", "disconnected": "Odpojené",
            "change_server": "Zmeniť server", "ready": "Pripravená",
            "listening": "Počúvam...", "thinking": "Premýšľam...", "speaking": "Hovorím...",
            "write_nova": "Napíš Nove...", "you": "Ty", "send": "Odoslať",
            "connect": "Pripojiť", "server_title": "Pripojenie k serveru",
            "speech_recognition": "Rozpoznávanie reči", "stt_connected": "Pripojené",
            "stt_loading": "Načítavam model...", "stt_error": "Chyba načítania", "stt_offline": "Nepripojené",
            "stt_desc": "WhisperKit on-device, automatická detekcia jazyka",
            "voice_id": "Voice ID", "voice_profile_active": "Hlasový profil aktívny",
            "voice_profile_none": "Hlasový profil nevytvorený",
            "voice_responds_you": "Nova reaguje iba na teba", "face_id_voice": "Face ID pre tvoj hlas",
            "create_profile": "Vytvoriť profil", "manage_profile": "Spravovať profil",
            "require_verification": "Vyžadovať overenie hlasu",
            "verify_on": "Nova reaguje iba keď rozpozná tvoj hlas",
            "verify_off": "Nova reaguje na všetkých hovoriacich",
            "verification_strict": "Prísnosť overenia", "last_match": "Posledná zhoda",
            "permissive": "Mierny", "balanced": "Vyvážený", "strict": "Prísny",
            "quick_actions": "Rýchle akcie", "quick_actions_desc": "Tlačidlá v hlavnom chate — ťukni pre okamžitú akciu",
            "action_name": "Názov", "action_prompt": "Čo povedať Nove...", "add_action": "Pridať akciu",
            "about": "O aplikácii", "version": "Verzia", "developer": "Vývojár",
            "delete_history": "Zmazať históriu", "delete_history_confirm": "Zmazať históriu?",
            "delete_history_msg": "Táto akcia je nezvratná. Všetky správy budú zmazané.",
            "delete": "Zmazať", "what_today": "Čo dnes potrebuješ?",
            "voice_unrecognized": "Hlas nerozpoznaný",
            "dev_project": "Dev projekt",
            "memory": "Pamäť Novy", "memory_facts": "Čo si Nova pamätá",
            "memory_empty": "Nova si zatiaľ nič nepamätá", "memory_delete_confirm": "Zmazať túto spomienku?",
            "memory_clear_all": "Zmazať všetko", "memory_clear_confirm": "Zmazať všetky spomienky?",
            "memory_count": "spomienok",
        ],
        "tr": [
            "settings": "Ayarlar", "save": "Kaydet", "name": "Ad", "cancel": "İptal",
            "personal_ai": "Kişisel yapay zeka asistanın", "mac_server_info": "Mac sunucun Claude Code çalıştırıyor",
            "speak_now": "Konuş...", "welcome_nova": "Nova'ya hoş geldin", "token_label": "Güvenlik jetonu",
            "setup_desc": "Bağlanmak için Mac sunucu adresini ve güvenlik jetonunu gir.",
            "name_placeholder": "Adın", "city": "Şehir",
            "city_placeholder": "Şehir", "language": "Dil",
            "voice": "Asistan sesi", "female": "Kadın", "male": "Erkek",
            "connection": "Bağlantı", "connected": "Bağlı", "disconnected": "Bağlantı kesildi",
            "change_server": "Sunucuyu değiştir", "ready": "Hazır",
            "listening": "Dinliyorum...", "thinking": "Düşünüyorum...", "speaking": "Konuşuyorum...",
            "write_nova": "Nova'ya yaz...", "you": "Sen", "send": "Gönder",
            "connect": "Bağlan", "server_title": "Sunucuya bağlan",
            "speech_recognition": "Konuşma tanıma", "stt_connected": "Bağlı",
            "stt_loading": "Model yükleniyor...", "stt_error": "Yükleme hatası", "stt_offline": "Çevrimdışı",
            "stt_desc": "WhisperKit cihaz üzerinde, otomatik dil algılama",
            "voice_id": "Voice ID", "voice_profile_active": "Ses profili etkin",
            "voice_profile_none": "Ses profili oluşturulmadı",
            "voice_responds_you": "Nova yalnızca sana yanıt verir", "face_id_voice": "Sesin için Face ID",
            "create_profile": "Profil oluştur", "manage_profile": "Profili yönet",
            "require_verification": "Ses doğrulaması iste",
            "verify_on": "Nova yalnızca sesin tanındığında yanıt verir",
            "verify_off": "Nova tüm konuşmacılara yanıt verir",
            "verification_strict": "Doğrulama hassasiyeti", "last_match": "Son eşleşme",
            "permissive": "Esnek", "balanced": "Dengeli", "strict": "Katı",
            "quick_actions": "Hızlı eylemler", "quick_actions_desc": "Sohbette düğmeler — anında eylem için dokun",
            "action_name": "Ad", "action_prompt": "Nova'ya ne söylenmeli...", "add_action": "Eylem ekle",
            "about": "Hakkında", "version": "Sürüm", "developer": "Geliştirici",
            "delete_history": "Geçmişi sil", "delete_history_confirm": "Geçmişi silmek istediğine emin misin?",
            "delete_history_msg": "Bu işlem geri alınamaz. Tüm mesajlar silinecek.",
            "delete": "Sil", "what_today": "Bugün neye ihtiyacın var?",
            "voice_unrecognized": "Ses tanınmadı",
            "dev_project": "Geliştirme projesi",
            "memory": "Nova'nın Hafızası", "memory_facts": "Nova'nın hatırladıkları",
            "memory_empty": "Nova henüz hiçbir şey hatırlamıyor", "memory_delete_confirm": "Bu anıyı sil?",
            "memory_clear_all": "Tümünü sil", "memory_clear_confirm": "Tüm anıları sil?",
            "memory_count": "anı",
        ],
    ]

    static func t(_ key: String) -> String {
        strings[current]?[key] ?? strings["en"]?[key] ?? key
    }

    // MARK: - Thinking stages (granular progress)
    static let stages: [String: [String: String]] = [
        "cs": [
            "thinking": "Přemýšlím",
            "understanding": "Rozumím, pracuji",
            "analyzing": "Analyzuji",
            "reading_file": "Čtu soubor",
            "writing_file": "Píšu do souboru",
            "writing_code": "Píšu kód",
            "editing_code": "Upravuji kód",
            "running_command": "Spouštím příkaz",
            "searching_web": "Hledám na webu",
            "searching_contact": "Hledám kontakt",
            "searching_restaurant": "Hledám restauraci",
            "searching_calendar": "Hledám v kalendáři",
            "calling_api": "Volám službu",
            "processing_image": "Zpracovávám obrázek",
            "processing_video": "Zpracovávám video",
            "analyzing_video": "Analyzuji video",
            "generating_response": "Formuluji odpověď",
            "composing": "Skládám odpověď",
            "explaining": "Vysvětluji",
            "recommending": "Připravuji doporučení",
            "comparing": "Porovnávám možnosti",
            "listing_steps": "Sestavuji postup",
            "summarizing": "Shrnuji",
            "warning": "Upozorňuji na rizika",
            "finishing": "Dokončuji",
            "needs_confirmation": "Potřebuji souhlas",
            "saving": "Ukládám změny",
            "browsing_results": "Procházím výsledky",
            "searching_deeper": "Hledám podrobněji",
            "preparing_report": "Připravuji report",
            "fetching_news": "Stahuji zprávy",
            "analyzing_news": "Analyzuji zprávy",
            "checking_weather": "Zjišťuji počasí",
            "searching_wiki": "Hledám na Wikipedii",
            "checking_exchange": "Zjišťuji kurzy",
            "searching_cinema": "Hledám program kin",
            "searching_tickets": "Hledám lístky",
            "searching_places": "Hledám místa",
            "reading_email": "Čtu emaily",
            "adding_calendar": "Zapisuji do kalendáře",
            "searching_files": "Procházím soubory",
            "searching_code": "Hledám v kódu",
            "building": "Builduji",
            "archiving": "Archivuji",
            "uploading_testflight": "Nahrávám na TestFlight",
            "installing_deps": "Instaluji závislosti",
            "running_tests": "Spouštím testy",
            "committing": "Commituji změny",
            "pushing": "Pushuji na remote",
            "reading_web": "Čtu webovou stránku",
        ],
        "en": [
            "thinking": "Thinking",
            "understanding": "Got it, working",
            "analyzing": "Analyzing",
            "reading_file": "Reading file",
            "writing_file": "Writing file",
            "writing_code": "Writing code",
            "editing_code": "Editing code",
            "running_command": "Running command",
            "searching_web": "Searching the web",
            "searching_contact": "Looking up contact",
            "searching_restaurant": "Finding a restaurant",
            "searching_calendar": "Checking calendar",
            "calling_api": "Calling service",
            "processing_image": "Processing image",
            "processing_video": "Processing video",
            "analyzing_video": "Analyzing video",
            "generating_response": "Forming response",
            "composing": "Composing reply",
            "explaining": "Explaining",
            "recommending": "Preparing recommendation",
            "comparing": "Comparing options",
            "listing_steps": "Listing steps",
            "summarizing": "Summarizing",
            "warning": "Flagging risks",
            "finishing": "Finishing up",
            "needs_confirmation": "Needs confirmation",
            "saving": "Saving changes",
            "browsing_results": "Browsing results",
            "searching_deeper": "Searching deeper",
            "preparing_report": "Preparing report",
            "fetching_news": "Fetching news",
            "analyzing_news": "Analyzing articles",
            "checking_weather": "Checking weather",
            "searching_wiki": "Searching Wikipedia",
            "checking_exchange": "Checking exchange rates",
            "searching_cinema": "Searching cinemas",
            "searching_tickets": "Searching tickets",
            "searching_places": "Searching places",
            "reading_email": "Reading emails",
            "adding_calendar": "Adding to calendar",
            "searching_files": "Browsing files",
            "searching_code": "Searching code",
            "building": "Building",
            "archiving": "Archiving",
            "uploading_testflight": "Uploading to TestFlight",
            "installing_deps": "Installing dependencies",
            "running_tests": "Running tests",
            "committing": "Committing changes",
            "pushing": "Pushing to remote",
            "reading_web": "Reading web page",
        ],
        "de": [
            "thinking": "Denke nach",
            "understanding": "Verstanden, arbeite",
            "analyzing": "Analysiere",
            "reading_file": "Lese Datei",
            "writing_file": "Schreibe Datei",
            "writing_code": "Schreibe Code",
            "editing_code": "Bearbeite Code",
            "running_command": "Führe Befehl aus",
            "searching_web": "Suche im Web",
            "searching_contact": "Suche Kontakt",
            "searching_restaurant": "Suche Restaurant",
            "searching_calendar": "Prüfe Kalender",
            "calling_api": "Rufe Dienst auf",
            "processing_image": "Verarbeite Bild",
            "processing_video": "Verarbeite Video",
            "analyzing_video": "Analysiere Video",
            "generating_response": "Formuliere Antwort",
            "composing": "Verfasse Antwort",
            "explaining": "Erkläre",
            "recommending": "Bereite Empfehlung vor",
            "comparing": "Vergleiche Optionen",
            "listing_steps": "Erstelle Schritte",
            "summarizing": "Fasse zusammen",
            "warning": "Weise auf Risiken hin",
            "finishing": "Schließe ab",
            "needs_confirmation": "Bestätigung nötig",
            "saving": "Speichere Änderungen",
            "browsing_results": "Durchsuche Ergebnisse",
            "searching_deeper": "Suche gründlicher",
            "preparing_report": "Erstelle Bericht",
            "fetching_news": "Lade Nachrichten",
            "analyzing_news": "Analysiere Artikel",
            "checking_weather": "Prüfe Wetter",
            "searching_wiki": "Suche auf Wikipedia",
            "checking_exchange": "Prüfe Wechselkurse",
            "searching_cinema": "Suche Kinoprogramm",
            "searching_tickets": "Suche Tickets",
            "searching_places": "Suche Orte",
            "reading_email": "Lese E-Mails",
            "adding_calendar": "Trage in Kalender ein",
            "searching_files": "Durchsuche Dateien",
            "searching_code": "Suche im Code",
            "building": "Baue", "archiving": "Archiviere",
            "uploading_testflight": "Lade auf TestFlight hoch",
            "installing_deps": "Installiere Abhängigkeiten",
            "running_tests": "Führe Tests aus",
            "committing": "Committe Änderungen", "pushing": "Pushe zum Remote",
        ],
        "fr": [
            "thinking": "Je réfléchis",
            "understanding": "Compris, je travaille",
            "analyzing": "J'analyse",
            "reading_file": "Lecture du fichier",
            "writing_file": "Écriture du fichier",
            "writing_code": "Écriture du code",
            "editing_code": "Modification du code",
            "running_command": "Exécution de la commande",
            "searching_web": "Recherche sur le web",
            "searching_contact": "Recherche du contact",
            "searching_restaurant": "Recherche de restaurant",
            "searching_calendar": "Consultation du calendrier",
            "calling_api": "Appel du service",
            "processing_image": "Traitement de l'image",
            "processing_video": "Traitement de la vidéo",
            "analyzing_video": "Analyse de la vidéo",
            "generating_response": "Formulation de la réponse",
            "composing": "Rédaction de la réponse",
            "explaining": "J'explique",
            "recommending": "Préparation des recommandations",
            "comparing": "Comparaison des options",
            "listing_steps": "Établissement des étapes",
            "summarizing": "Résumé",
            "warning": "Signalement des risques",
            "finishing": "Finalisation",
            "needs_confirmation": "Confirmation requise",
            "saving": "Enregistrement des modifications",
            "browsing_results": "Parcours des résultats",
            "searching_deeper": "Recherche approfondie",
            "preparing_report": "Préparation du rapport",
            "fetching_news": "Téléchargement des actualités",
            "analyzing_news": "Analyse des articles",
            "checking_weather": "Consultation de la météo",
            "searching_wiki": "Recherche sur Wikipédia",
            "checking_exchange": "Consultation des taux de change",
            "searching_cinema": "Recherche du programme cinéma",
            "searching_tickets": "Recherche de billets",
            "searching_places": "Recherche de lieux",
            "reading_email": "Lecture des e-mails",
            "adding_calendar": "Ajout au calendrier",
            "searching_files": "Parcours des fichiers",
            "searching_code": "Recherche dans le code",
            "building": "Compilation", "archiving": "Archivage",
            "uploading_testflight": "Envoi sur TestFlight",
            "installing_deps": "Installation des dépendances",
            "running_tests": "Exécution des tests",
            "committing": "Commit des modifications", "pushing": "Push vers le remote",
        ],
        "es": [
            "thinking": "Pensando",
            "understanding": "Entendido, trabajando",
            "analyzing": "Analizando",
            "reading_file": "Leyendo archivo",
            "writing_file": "Escribiendo archivo",
            "writing_code": "Escribiendo código",
            "editing_code": "Editando código",
            "running_command": "Ejecutando comando",
            "searching_web": "Buscando en la web",
            "searching_contact": "Buscando contacto",
            "searching_restaurant": "Buscando restaurante",
            "searching_calendar": "Consultando calendario",
            "calling_api": "Llamando al servicio",
            "processing_image": "Procesando imagen",
            "processing_video": "Procesando video",
            "analyzing_video": "Analizando video",
            "generating_response": "Formulando respuesta",
            "composing": "Componiendo respuesta",
            "explaining": "Explicando",
            "recommending": "Preparando recomendación",
            "comparing": "Comparando opciones",
            "listing_steps": "Listando pasos",
            "summarizing": "Resumiendo",
            "warning": "Señalando riesgos",
            "finishing": "Finalizando",
            "needs_confirmation": "Necesita confirmación",
            "saving": "Guardando cambios",
            "browsing_results": "Revisando resultados",
            "searching_deeper": "Buscando más a fondo",
            "preparing_report": "Preparando informe",
            "fetching_news": "Descargando noticias",
            "analyzing_news": "Analizando artículos",
            "checking_weather": "Consultando el clima",
            "searching_wiki": "Buscando en Wikipedia",
            "checking_exchange": "Consultando tipos de cambio",
            "searching_cinema": "Buscando cartelera",
            "searching_tickets": "Buscando entradas",
            "searching_places": "Buscando lugares",
            "reading_email": "Leyendo correos",
            "adding_calendar": "Agregando al calendario",
            "searching_files": "Buscando archivos",
            "searching_code": "Buscando en el código",
            "building": "Compilando", "archiving": "Archivando",
            "uploading_testflight": "Subiendo a TestFlight",
            "installing_deps": "Instalando dependencias",
            "running_tests": "Ejecutando pruebas",
            "committing": "Haciendo commit", "pushing": "Haciendo push",
        ],
        "ja": [
            "thinking": "考え中",
            "understanding": "了解、作業中",
            "analyzing": "分析中",
            "reading_file": "ファイルを読み込み中",
            "writing_file": "ファイルを書き込み中",
            "writing_code": "コードを作成中",
            "editing_code": "コードを編集中",
            "running_command": "コマンドを実行中",
            "searching_web": "ウェブを検索中",
            "searching_contact": "連絡先を検索中",
            "searching_restaurant": "レストランを検索中",
            "searching_calendar": "カレンダーを確認中",
            "calling_api": "サービスを呼び出し中",
            "processing_image": "画像を処理中",
            "processing_video": "動画を処理中",
            "analyzing_video": "動画を分析中",
            "generating_response": "返答を構成中",
            "composing": "返答を作成中",
            "explaining": "説明中",
            "recommending": "推奨を準備中",
            "comparing": "選択肢を比較中",
            "listing_steps": "手順を整理中",
            "summarizing": "まとめ中",
            "warning": "リスクを指摘中",
            "finishing": "完了中",
            "needs_confirmation": "確認が必要",
            "saving": "変更を保存中",
            "browsing_results": "結果を閲覧中",
            "searching_deeper": "詳細検索中",
            "preparing_report": "レポートを作成中",
            "fetching_news": "ニュースを取得中",
            "analyzing_news": "記事を分析中",
            "checking_weather": "天気を確認中",
            "searching_wiki": "Wikipediaで検索中",
            "checking_exchange": "為替レートを確認中",
            "searching_cinema": "映画館を検索中",
            "searching_tickets": "チケット検索中",
            "searching_places": "場所を検索中",
            "reading_email": "メールを読み込み中",
            "adding_calendar": "カレンダーに追加中",
            "searching_files": "ファイルを検索中",
            "searching_code": "コード内を検索中",
            "building": "ビルド中", "archiving": "アーカイブ中",
            "uploading_testflight": "TestFlightにアップロード中",
            "installing_deps": "依存関係をインストール中",
            "running_tests": "テストを実行中",
            "committing": "コミット中", "pushing": "プッシュ中",
        ],
        "zh": [
            "thinking": "思考中",
            "understanding": "收到，处理中",
            "analyzing": "分析中",
            "reading_file": "正在读取文件",
            "writing_file": "正在写入文件",
            "writing_code": "正在编写代码",
            "editing_code": "正在编辑代码",
            "running_command": "正在执行命令",
            "searching_web": "正在搜索网络",
            "searching_contact": "正在查找联系人",
            "searching_restaurant": "正在查找餐厅",
            "searching_calendar": "正在查看日历",
            "calling_api": "正在调用服务",
            "processing_image": "正在处理图片",
            "processing_video": "正在处理视频",
            "analyzing_video": "正在分析视频",
            "generating_response": "正在组织回复",
            "composing": "正在撰写回复",
            "explaining": "正在解释",
            "recommending": "正在准备建议",
            "comparing": "正在比较选项",
            "listing_steps": "正在列出步骤",
            "summarizing": "正在总结",
            "warning": "正在提示风险",
            "finishing": "即将完成",
            "needs_confirmation": "需要确认",
            "saving": "正在保存更改",
            "browsing_results": "正在浏览结果",
            "searching_deeper": "正在深入搜索",
            "preparing_report": "正在准备报告",
            "fetching_news": "正在获取新闻",
            "analyzing_news": "正在分析文章",
            "checking_weather": "正在查看天气",
            "searching_wiki": "正在搜索维基百科",
            "checking_exchange": "正在查看汇率",
            "searching_cinema": "正在搜索电影院",
            "searching_tickets": "搜索票务",
            "searching_places": "正在搜索地点",
            "reading_email": "正在阅读邮件",
            "adding_calendar": "正在添加到日历",
            "searching_files": "正在浏览文件",
            "searching_code": "正在搜索代码",
            "building": "正在构建", "archiving": "正在归档",
            "uploading_testflight": "正在上传到TestFlight",
            "installing_deps": "正在安装依赖",
            "running_tests": "正在运行测试",
            "committing": "正在提交更改", "pushing": "正在推送到远程",
        ],
        "ar": [
            "thinking": "أفكّر",
            "understanding": "فهمت، أعمل على ذلك",
            "analyzing": "أحلّل",
            "reading_file": "أقرأ الملف",
            "writing_file": "أكتب في الملف",
            "writing_code": "أكتب كوداً",
            "editing_code": "أعدّل الكود",
            "running_command": "أنفّذ أمراً",
            "searching_web": "أبحث في الويب",
            "searching_contact": "أبحث عن جهة اتصال",
            "searching_restaurant": "أبحث عن مطعم",
            "searching_calendar": "أتحقق من التقويم",
            "calling_api": "أستدعي الخدمة",
            "processing_image": "أعالج الصورة",
            "processing_video": "أعالج الفيديو",
            "analyzing_video": "أحلل الفيديو",
            "generating_response": "أصيغ الردّ",
            "composing": "أؤلّف الردّ",
            "explaining": "أشرح",
            "recommending": "أحضّر التوصيات",
            "comparing": "أقارن الخيارات",
            "listing_steps": "أرتّب الخطوات",
            "summarizing": "ألخّص",
            "warning": "أنبّه على المخاطر",
            "finishing": "أنهي",
            "needs_confirmation": "يلزم التأكيد",
            "saving": "أحفظ التغييرات",
            "browsing_results": "أتصفّح النتائج",
            "searching_deeper": "أبحث بعمق أكبر",
            "preparing_report": "أحضّر التقرير",
            "fetching_news": "أجلب الأخبار",
            "analyzing_news": "أحلّل المقالات",
            "checking_weather": "أتحقق من الطقس",
            "searching_wiki": "أبحث في ويكيبيديا",
            "checking_exchange": "أتحقق من أسعار الصرف",
            "searching_cinema": "أبحث عن السينما",
            "searching_tickets": "أبحث عن تذاكر",
            "searching_places": "أبحث عن أماكن",
            "reading_email": "أقرأ البريد",
            "adding_calendar": "أضيف إلى التقويم",
            "searching_files": "أتصفّح الملفات",
            "searching_code": "أبحث في الكود",
            "building": "أبني", "archiving": "أؤرشف",
            "uploading_testflight": "أرفع إلى TestFlight",
            "installing_deps": "أثبّت التبعيات",
            "running_tests": "أنفّذ الاختبارات",
            "committing": "أعمل Commit", "pushing": "أعمل Push",
            "reading_web": "أقرأ صفحة الويب",
        ],
        "hi": [
            "thinking": "सोच रही हूँ",
            "understanding": "समझ गई, काम कर रही हूँ",
            "analyzing": "विश्लेषण कर रही हूँ",
            "reading_file": "फ़ाइल पढ़ रही हूँ",
            "writing_file": "फ़ाइल लिख रही हूँ",
            "writing_code": "कोड लिख रही हूँ",
            "editing_code": "कोड संपादित कर रही हूँ",
            "running_command": "कमांड चला रही हूँ",
            "searching_web": "वेब पर खोज रही हूँ",
            "searching_contact": "संपर्क खोज रही हूँ",
            "searching_restaurant": "रेस्तराँ खोज रही हूँ",
            "searching_calendar": "कैलेंडर देख रही हूँ",
            "calling_api": "सेवा को कॉल कर रही हूँ",
            "processing_image": "छवि प्रोसेस कर रही हूँ",
            "processing_video": "वीडियो प्रोसेस कर रही हूँ",
            "analyzing_video": "वीडियो का विश्लेषण कर रही हूँ",
            "generating_response": "उत्तर तैयार कर रही हूँ",
            "composing": "जवाब लिख रही हूँ",
            "explaining": "समझा रही हूँ",
            "recommending": "सिफ़ारिश तैयार कर रही हूँ",
            "comparing": "विकल्पों की तुलना कर रही हूँ",
            "listing_steps": "चरण बना रही हूँ",
            "summarizing": "सारांश बना रही हूँ",
            "warning": "जोखिम बता रही हूँ",
            "finishing": "पूरा कर रही हूँ",
            "needs_confirmation": "पुष्टि आवश्यक",
            "saving": "बदलाव सहेज रही हूँ",
            "browsing_results": "परिणाम देख रही हूँ",
            "searching_deeper": "गहराई से खोज रही हूँ",
            "preparing_report": "रिपोर्ट तैयार कर रही हूँ",
            "fetching_news": "समाचार ला रही हूँ",
            "analyzing_news": "लेख विश्लेषित कर रही हूँ",
            "checking_weather": "मौसम देख रही हूँ",
            "searching_wiki": "विकिपीडिया पर खोज रही हूँ",
            "checking_exchange": "विनिमय दर देख रही हूँ",
            "searching_cinema": "सिनेमा खोज रही हूँ",
            "searching_tickets": "टिकट खोज रही हूँ",
            "searching_places": "स्थान खोज रही हूँ",
            "reading_email": "ईमेल पढ़ रही हूँ",
            "adding_calendar": "कैलेंडर में जोड़ रही हूँ",
            "searching_files": "फ़ाइलें खोज रही हूँ",
            "searching_code": "कोड में खोज रही हूँ",
            "building": "बिल्ड कर रही हूँ", "archiving": "आर्काइव कर रही हूँ",
            "uploading_testflight": "TestFlight पर अपलोड कर रही हूँ",
            "installing_deps": "डिपेंडेंसी इंस्टॉल कर रही हूँ",
            "running_tests": "टेस्ट चला रही हूँ",
            "committing": "कमिट कर रही हूँ", "pushing": "पुश कर रही हूँ",
            "reading_web": "वेब पेज पढ़ रही हूँ",
        ],
        "it": [
            "thinking": "Sto pensando",
            "understanding": "Capito, ci lavoro",
            "analyzing": "Analizzo",
            "reading_file": "Leggo il file",
            "writing_file": "Scrivo il file",
            "writing_code": "Scrivo codice",
            "editing_code": "Modifico il codice",
            "running_command": "Eseguo il comando",
            "searching_web": "Cerco sul web",
            "searching_contact": "Cerco il contatto",
            "searching_restaurant": "Cerco un ristorante",
            "searching_calendar": "Controllo il calendario",
            "calling_api": "Chiamo il servizio",
            "processing_image": "Elaboro l'immagine",
            "processing_video": "Elaboro il video",
            "analyzing_video": "Analizzo il video",
            "generating_response": "Formulo la risposta",
            "composing": "Compongo la risposta",
            "explaining": "Spiego",
            "recommending": "Preparo i consigli",
            "comparing": "Confronto le opzioni",
            "listing_steps": "Elenco i passaggi",
            "summarizing": "Riassumo",
            "warning": "Segnalo i rischi",
            "finishing": "Sto finendo",
            "needs_confirmation": "Serve conferma",
            "saving": "Salvo le modifiche",
            "browsing_results": "Sfoglio i risultati",
            "searching_deeper": "Cerco più a fondo",
            "preparing_report": "Preparo il report",
            "fetching_news": "Scarico le notizie",
            "analyzing_news": "Analizzo gli articoli",
            "checking_weather": "Controllo il meteo",
            "searching_wiki": "Cerco su Wikipedia",
            "checking_exchange": "Controllo i tassi di cambio",
            "searching_cinema": "Cerco i cinema",
            "searching_tickets": "Cerco biglietti",
            "searching_places": "Cerco luoghi",
            "reading_email": "Leggo le email",
            "adding_calendar": "Aggiungo al calendario",
            "searching_files": "Sfoglio i file",
            "searching_code": "Cerco nel codice",
            "building": "Compilo", "archiving": "Archivio",
            "uploading_testflight": "Carico su TestFlight",
            "installing_deps": "Installo le dipendenze",
            "running_tests": "Eseguo i test",
            "committing": "Commit delle modifiche", "pushing": "Push al remote",
            "reading_web": "Leggo la pagina web",
        ],
        "ko": [
            "thinking": "생각 중",
            "understanding": "알겠습니다, 작업 중",
            "analyzing": "분석 중",
            "reading_file": "파일 읽는 중",
            "writing_file": "파일 쓰는 중",
            "writing_code": "코드 작성 중",
            "editing_code": "코드 수정 중",
            "running_command": "명령 실행 중",
            "searching_web": "웹 검색 중",
            "searching_contact": "연락처 검색 중",
            "searching_restaurant": "레스토랑 검색 중",
            "searching_calendar": "캘린더 확인 중",
            "calling_api": "서비스 호출 중",
            "processing_image": "이미지 처리 중",
            "processing_video": "동영상 처리 중",
            "analyzing_video": "동영상 분석 중",
            "generating_response": "응답 작성 중",
            "composing": "답변 구성 중",
            "explaining": "설명 중",
            "recommending": "추천 준비 중",
            "comparing": "옵션 비교 중",
            "listing_steps": "단계 정리 중",
            "summarizing": "요약 중",
            "warning": "위험 알림",
            "finishing": "마무리 중",
            "needs_confirmation": "확인 필요",
            "saving": "변경 사항 저장 중",
            "browsing_results": "결과 탐색 중",
            "searching_deeper": "심층 검색 중",
            "preparing_report": "보고서 준비 중",
            "fetching_news": "뉴스 가져오는 중",
            "analyzing_news": "기사 분석 중",
            "checking_weather": "날씨 확인 중",
            "searching_wiki": "위키백과 검색 중",
            "checking_exchange": "환율 확인 중",
            "searching_cinema": "영화관 검색 중",
            "searching_tickets": "티켓 검색 중",
            "searching_places": "장소 검색 중",
            "reading_email": "이메일 읽는 중",
            "adding_calendar": "캘린더에 추가 중",
            "searching_files": "파일 탐색 중",
            "searching_code": "코드 검색 중",
            "building": "빌드 중", "archiving": "아카이브 중",
            "uploading_testflight": "TestFlight에 업로드 중",
            "installing_deps": "의존성 설치 중",
            "running_tests": "테스트 실행 중",
            "committing": "커밋 중", "pushing": "푸시 중",
            "reading_web": "웹 페이지 읽는 중",
        ],
        "pl": [
            "thinking": "Myślę",
            "understanding": "Rozumiem, pracuję",
            "analyzing": "Analizuję",
            "reading_file": "Czytam plik",
            "writing_file": "Zapisuję plik",
            "writing_code": "Piszę kod",
            "editing_code": "Edytuję kod",
            "running_command": "Uruchamiam polecenie",
            "searching_web": "Szukam w sieci",
            "searching_contact": "Szukam kontaktu",
            "searching_restaurant": "Szukam restauracji",
            "searching_calendar": "Sprawdzam kalendarz",
            "calling_api": "Wywołuję usługę",
            "processing_image": "Przetwarzam obraz",
            "processing_video": "Przetwarzam wideo",
            "analyzing_video": "Analizuję wideo",
            "generating_response": "Formułuję odpowiedź",
            "composing": "Tworzę odpowiedź",
            "explaining": "Wyjaśniam",
            "recommending": "Przygotowuję rekomendację",
            "comparing": "Porównuję opcje",
            "listing_steps": "Układam kroki",
            "summarizing": "Podsumowuję",
            "warning": "Wskazuję zagrożenia",
            "finishing": "Kończę",
            "needs_confirmation": "Wymagane potwierdzenie",
            "saving": "Zapisuję zmiany",
            "browsing_results": "Przeglądam wyniki",
            "searching_deeper": "Szukam dokładniej",
            "preparing_report": "Przygotowuję raport",
            "fetching_news": "Pobieram wiadomości",
            "analyzing_news": "Analizuję artykuły",
            "checking_weather": "Sprawdzam pogodę",
            "searching_wiki": "Szukam na Wikipedii",
            "checking_exchange": "Sprawdzam kursy walut",
            "searching_cinema": "Szukam programu kin",
            "searching_tickets": "Szukam biletów",
            "searching_places": "Szukam miejsc",
            "reading_email": "Czytam e-maile",
            "adding_calendar": "Dodaję do kalendarza",
            "searching_files": "Przeglądam pliki",
            "searching_code": "Szukam w kodzie",
            "building": "Buduję", "archiving": "Archiwizuję",
            "uploading_testflight": "Wgrywam na TestFlight",
            "installing_deps": "Instaluję zależności",
            "running_tests": "Uruchamiam testy",
            "committing": "Commituję zmiany", "pushing": "Pushuję na remote",
            "reading_web": "Czytam stronę internetową",
        ],
        "pt": [
            "thinking": "Pensando",
            "understanding": "Entendi, trabalhando",
            "analyzing": "Analisando",
            "reading_file": "Lendo arquivo",
            "writing_file": "Escrevendo arquivo",
            "writing_code": "Escrevendo código",
            "editing_code": "Editando código",
            "running_command": "Executando comando",
            "searching_web": "Pesquisando na web",
            "searching_contact": "Procurando contato",
            "searching_restaurant": "Procurando restaurante",
            "searching_calendar": "Verificando calendário",
            "calling_api": "Chamando serviço",
            "processing_image": "Processando imagem",
            "processing_video": "Processando vídeo",
            "analyzing_video": "Analisando vídeo",
            "generating_response": "Formulando resposta",
            "composing": "Compondo resposta",
            "explaining": "Explicando",
            "recommending": "Preparando recomendação",
            "comparing": "Comparando opções",
            "listing_steps": "Listando etapas",
            "summarizing": "Resumindo",
            "warning": "Alertando sobre riscos",
            "finishing": "Finalizando",
            "needs_confirmation": "Precisa de confirmação",
            "saving": "Salvando alterações",
            "browsing_results": "Navegando nos resultados",
            "searching_deeper": "Pesquisando mais a fundo",
            "preparing_report": "Preparando relatório",
            "fetching_news": "Buscando notícias",
            "analyzing_news": "Analisando artigos",
            "checking_weather": "Verificando o clima",
            "searching_wiki": "Pesquisando na Wikipédia",
            "checking_exchange": "Verificando câmbio",
            "searching_cinema": "Pesquisando cinemas",
            "searching_tickets": "Procurando ingressos",
            "searching_places": "Pesquisando lugares",
            "reading_email": "Lendo e-mails",
            "adding_calendar": "Adicionando ao calendário",
            "searching_files": "Navegando nos arquivos",
            "searching_code": "Pesquisando no código",
            "building": "Compilando", "archiving": "Arquivando",
            "uploading_testflight": "Enviando para TestFlight",
            "installing_deps": "Instalando dependências",
            "running_tests": "Executando testes",
            "committing": "Fazendo commit", "pushing": "Fazendo push",
            "reading_web": "Lendo página web",
        ],
        "ru": [
            "thinking": "Думаю",
            "understanding": "Поняла, работаю",
            "analyzing": "Анализирую",
            "reading_file": "Читаю файл",
            "writing_file": "Записываю файл",
            "writing_code": "Пишу код",
            "editing_code": "Редактирую код",
            "running_command": "Выполняю команду",
            "searching_web": "Ищу в интернете",
            "searching_contact": "Ищу контакт",
            "searching_restaurant": "Ищу ресторан",
            "searching_calendar": "Проверяю календарь",
            "calling_api": "Вызываю сервис",
            "processing_image": "Обрабатываю изображение",
            "processing_video": "Обрабатываю видео",
            "analyzing_video": "Анализирую видео",
            "generating_response": "Формулирую ответ",
            "composing": "Составляю ответ",
            "explaining": "Объясняю",
            "recommending": "Готовлю рекомендацию",
            "comparing": "Сравниваю варианты",
            "listing_steps": "Составляю шаги",
            "summarizing": "Подвожу итог",
            "warning": "Предупреждаю о рисках",
            "finishing": "Завершаю",
            "needs_confirmation": "Нужно подтверждение",
            "saving": "Сохраняю изменения",
            "browsing_results": "Просматриваю результаты",
            "searching_deeper": "Ищу подробнее",
            "preparing_report": "Готовлю отчёт",
            "fetching_news": "Загружаю новости",
            "analyzing_news": "Анализирую статьи",
            "checking_weather": "Проверяю погоду",
            "searching_wiki": "Ищу в Википедии",
            "checking_exchange": "Проверяю курсы валют",
            "searching_cinema": "Ищу кинотеатры",
            "searching_tickets": "Ищу билеты",
            "searching_places": "Ищу места",
            "reading_email": "Читаю почту",
            "adding_calendar": "Добавляю в календарь",
            "searching_files": "Просматриваю файлы",
            "searching_code": "Ищу в коде",
            "building": "Собираю", "archiving": "Архивирую",
            "uploading_testflight": "Загружаю на TestFlight",
            "installing_deps": "Устанавливаю зависимости",
            "running_tests": "Запускаю тесты",
            "committing": "Делаю коммит", "pushing": "Делаю пуш",
            "reading_web": "Читаю веб-страницу",
        ],
        "sk": [
            "thinking": "Premýšľam",
            "understanding": "Rozumiem, pracujem",
            "analyzing": "Analyzujem",
            "reading_file": "Čítam súbor",
            "writing_file": "Píšem do súboru",
            "writing_code": "Píšem kód",
            "editing_code": "Upravujem kód",
            "running_command": "Spúšťam príkaz",
            "searching_web": "Hľadám na webe",
            "searching_contact": "Hľadám kontakt",
            "searching_restaurant": "Hľadám reštauráciu",
            "searching_calendar": "Kontrolujem kalendár",
            "calling_api": "Volám službu",
            "processing_image": "Spracúvam obrázok",
            "processing_video": "Spracúvam video",
            "analyzing_video": "Analyzujem video",
            "generating_response": "Formulujem odpoveď",
            "composing": "Skladám odpoveď",
            "explaining": "Vysvetľujem",
            "recommending": "Pripravujem odporúčanie",
            "comparing": "Porovnávam možnosti",
            "listing_steps": "Zostavujem postup",
            "summarizing": "Zhŕňam",
            "warning": "Upozorňujem na riziká",
            "finishing": "Dokončujem",
            "needs_confirmation": "Potrebujem súhlas",
            "saving": "Ukladám zmeny",
            "browsing_results": "Prechádzam výsledky",
            "searching_deeper": "Hľadám podrobnejšie",
            "preparing_report": "Pripravujem report",
            "fetching_news": "Sťahujem správy",
            "analyzing_news": "Analyzujem správy",
            "checking_weather": "Zisťujem počasie",
            "searching_wiki": "Hľadám na Wikipédii",
            "checking_exchange": "Zisťujem kurzy",
            "searching_cinema": "Hľadám program kín",
            "searching_tickets": "Hľadám lístky",
            "searching_places": "Hľadám miesta",
            "reading_email": "Čítam e-maily",
            "adding_calendar": "Zapisujem do kalendára",
            "searching_files": "Prechádzam súbory",
            "searching_code": "Hľadám v kóde",
            "building": "Buildujem", "archiving": "Archivujem",
            "uploading_testflight": "Nahrávam na TestFlight",
            "installing_deps": "Inštalujem závislosti",
            "running_tests": "Spúšťam testy",
            "committing": "Commitujem zmeny", "pushing": "Pushujem na remote",
            "reading_web": "Čítam webovú stránku",
        ],
        "tr": [
            "thinking": "Düşünüyorum",
            "understanding": "Anladım, çalışıyorum",
            "analyzing": "Analiz ediyorum",
            "reading_file": "Dosya okuyorum",
            "writing_file": "Dosya yazıyorum",
            "writing_code": "Kod yazıyorum",
            "editing_code": "Kod düzenliyorum",
            "running_command": "Komut çalıştırıyorum",
            "searching_web": "Web'de arıyorum",
            "searching_contact": "Kişi arıyorum",
            "searching_restaurant": "Restoran arıyorum",
            "searching_calendar": "Takvimi kontrol ediyorum",
            "calling_api": "Servis çağırıyorum",
            "processing_image": "Görüntü işliyorum",
            "processing_video": "Video işliyorum",
            "analyzing_video": "Video analiz ediyorum",
            "generating_response": "Yanıt oluşturuyorum",
            "composing": "Cevap yazıyorum",
            "explaining": "Açıklıyorum",
            "recommending": "Öneri hazırlıyorum",
            "comparing": "Seçenekleri karşılaştırıyorum",
            "listing_steps": "Adımları sıralıyorum",
            "summarizing": "Özetliyorum",
            "warning": "Riskleri belirtiyorum",
            "finishing": "Bitiriyorum",
            "needs_confirmation": "Onay gerekli",
            "saving": "Değişiklikleri kaydediyorum",
            "browsing_results": "Sonuçları inceliyorum",
            "searching_deeper": "Daha derinlemesine arıyorum",
            "preparing_report": "Rapor hazırlıyorum",
            "fetching_news": "Haberleri getiriyorum",
            "analyzing_news": "Makaleleri analiz ediyorum",
            "checking_weather": "Hava durumunu kontrol ediyorum",
            "searching_wiki": "Vikipedi'de arıyorum",
            "checking_exchange": "Döviz kurlarını kontrol ediyorum",
            "searching_cinema": "Sinema arıyorum",
            "searching_tickets": "Bilet arıyorum",
            "searching_places": "Yer arıyorum",
            "reading_email": "E-posta okuyorum",
            "adding_calendar": "Takvime ekliyorum",
            "searching_files": "Dosyaları tarayorum",
            "searching_code": "Kodda arıyorum",
            "building": "Derliyorum", "archiving": "Arşivliyorum",
            "uploading_testflight": "TestFlight'a yüklüyorum",
            "installing_deps": "Bağımlılıkları yüklüyorum",
            "running_tests": "Testleri çalıştırıyorum",
            "committing": "Commit yapıyorum", "pushing": "Push yapıyorum",
            "reading_web": "Web sayfası okuyorum",
        ],
    ]

    /// Return name in vocative case for current language.
    /// - Czech: applies heuristic declension rules covering ~80% of common names.
    /// - Other languages: returns name unchanged (Hello Mark, Hello Anna).
    static func vocative(_ name: String) -> String {
        let trimmed = name.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else { return trimmed }
        guard current == "cs" else { return trimmed }
        return czechVocative(trimmed)
    }

    private static func czechVocative(_ name: String) -> String {
        let lower = name.lowercased()
        // Irregular / exceptions (lowercase match)
        let exceptions: [String: String] = [
            "petr": "Petře", "pavel": "Pavle", "karel": "Karle",
            "bůh": "Bože", "otec": "Otče", "syn": "Synu",
            "ježíš": "Ježíši", "ondřej": "Ondřeji", "jiří": "Jiří",
            "matěj": "Matěji", "tomáš": "Tomáši", "lukáš": "Lukáši",
            "aleš": "Aleši", "jakub": "Jakube", "martin": "Martine",
            "david": "Davide", "adam": "Adame", "michal": "Michale",
            "honza": "Honzo", "jan": "Jane", "filip": "Filipe",
            "štěpán": "Štěpáne", "marek": "Marku", "radek": "Radku",
            "patrik": "Patriku", "vojtěch": "Vojtěchu", "roman": "Romane",
            "robert": "Roberte", "daniel": "Danieli", "dominik": "Dominiku",
            "ivan": "Ivane", "igor": "Igore", "josef": "Josefe",
        ]
        if let fixed = exceptions[lower] { return fixed }

        // -ie / -ia → unchanged (Marie, Sofia, Maria, Olivia)
        if lower.hasSuffix("ie") || lower.hasSuffix("ia") {
            return name
        }
        // Female name ending in -a → -o (Monika → Moniko, Jana → Jano)
        if lower.hasSuffix("a") {
            return String(name.dropLast()) + "o"
        }
        // Male -ej / -aj / -oj → add -i (Ondřej → Ondřeji, fallback if not in exceptions)
        if lower.hasSuffix("ej") || lower.hasSuffix("aj") || lower.hasSuffix("oj") {
            return name + "i"
        }
        // Male ending in soft consonant (č, š, ž, ř, j, ť, ď, ň, c) → -i
        let lastChar = lower.last!
        let softConsonants: Set<Character> = ["č", "š", "ž", "ř", "j", "c"]
        if softConsonants.contains(lastChar) {
            return name + "i"
        }
        // Ending in -l → -le (Pavel handled, fallback)
        if lower.hasSuffix("el") {
            return String(name.dropLast(2)) + "le"
        }
        // Default: male hard consonant → -e
        return name + "e"
    }

    static func stage(_ key: String?, detail: String? = nil) -> String {
        let lang = current
        let resolvedKey = key ?? "thinking"
        let label = stages[lang]?[resolvedKey] ?? stages["en"]?[resolvedKey] ?? stages["en"]?["thinking"] ?? "Thinking"
        if let detail = detail, !detail.isEmpty {
            // Prémiový formát: "Čtu soubor (ContentView.swift)" místo "Čtu soubor: ContentView.swift"
            return "\(label)  ·  \(detail)"
        }
        return label
    }
}
